// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if AnswerRecords
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Detail feedback of Agent Assist result.
  public struct AgentAssistantFeedback: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Whether or not the suggested answer is relevant.
    ///
    /// For example:
    ///
    /// * Query: "Can I change my mailing address?"
    /// * Suggested document says: "Items must be returned/exchanged within 60
    ///   days of the purchase date."
    /// * [answer_relevance][google.cloud.dialogflow.v2.AgentAssistantFeedback.answer_relevance]: [AnswerRelevance.IRRELEVANT][google.cloud.dialogflow.v2.AgentAssistantFeedback.AnswerRelevance.IRRELEVANT]
    ///
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.AnswerRelevance.IRRELEVANT]: <doc:AgentAssistantFeedback/AnswerRelevance/irrelevant>
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.answer_relevance]: <doc:AgentAssistantFeedback/answerRelevance>
    public var answerRelevance: AgentAssistantFeedback.AnswerRelevance =
      AgentAssistantFeedback.AnswerRelevance()

    /// Optional. Whether or not the information in the document is correct.
    ///
    /// For example:
    ///
    /// * Query: "Can I return the package in 2 days once received?"
    /// * Suggested document says: "Items must be returned/exchanged within 60
    ///   days of the purchase date."
    /// * Ground truth: "No return or exchange is allowed."
    /// * [document_correctness][google.cloud.dialogflow.v2.AgentAssistantFeedback.document_correctness]: [INCORRECT][google.cloud.dialogflow.v2.AgentAssistantFeedback.DocumentCorrectness.INCORRECT]
    ///
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.DocumentCorrectness.INCORRECT]: <doc:AgentAssistantFeedback/DocumentCorrectness/incorrect>
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.document_correctness]: <doc:AgentAssistantFeedback/documentCorrectness>
    public var documentCorrectness: AgentAssistantFeedback.DocumentCorrectness =
      AgentAssistantFeedback.DocumentCorrectness()

    /// Optional. Whether or not the suggested document is efficient. For example,
    /// if the document is poorly written, hard to understand, hard to use or
    /// too long to find useful information,
    /// [document_efficiency][google.cloud.dialogflow.v2.AgentAssistantFeedback.document_efficiency]
    /// is
    /// [DocumentEfficiency.INEFFICIENT][google.cloud.dialogflow.v2.AgentAssistantFeedback.DocumentEfficiency.INEFFICIENT].
    ///
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.DocumentEfficiency.INEFFICIENT]: <doc:AgentAssistantFeedback/DocumentEfficiency/inefficient>
    /// [google.cloud.dialogflow.v2.AgentAssistantFeedback.document_efficiency]: <doc:AgentAssistantFeedback/documentEfficiency>
    public var documentEfficiency: AgentAssistantFeedback.DocumentEfficiency =
      AgentAssistantFeedback.DocumentEfficiency()

    /// Optional. Feedback for conversation summarization.
    public var summarizationFeedback: AgentAssistantFeedback.SummarizationFeedback? = nil

    /// Optional. Feedback for knowledge search.
    public var knowledgeSearchFeedback: AgentAssistantFeedback.KnowledgeSearchFeedback? = nil

    /// Optional. Feedback for knowledge assist.
    public var knowledgeAssistFeedback: AgentAssistantFeedback.KnowledgeAssistFeedback? = nil

    /// Initialize a new instance of `AgentAssistantFeedback`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = AgentAssistantFeedback().with { $0.answerRelevance = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Feedback for conversation summarization.
    public struct SummarizationFeedback: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Timestamp when composing of the summary starts.
      public var startTime: GoogleCloudWKT.Timestamp? = nil

      /// Timestamp when the summary was submitted.
      public var submitTime: GoogleCloudWKT.Timestamp? = nil

      /// Text of actual submitted summary.
      public var summaryText: Swift.String = Swift.String()

      /// Optional. Actual text sections of submitted summary.
      public var textSections: [Swift.String: Swift.String] = [:]

      /// Initialize a new instance of `SummarizationFeedback`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SummarizationFeedback().with { $0.startTime = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dialogflow.v2.AgentAssistantFeedback.SummarizationFeedback"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Feedback for knowledge search.
    public struct KnowledgeSearchFeedback: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Whether the answer was copied by the human agent or not.
      /// If the value is set to be true,
      /// [AnswerFeedback.clicked][google.cloud.dialogflow.v2.AnswerFeedback.clicked]
      /// will be updated to be true.
      ///
      /// [google.cloud.dialogflow.v2.AnswerFeedback.clicked]: <doc:AnswerFeedback/clicked>
      public var answerCopied: Swift.Bool = Swift.Bool()

      /// The URIs clicked by the human agent. The value is appended for each
      /// [UpdateAnswerRecordRequest][google.cloud.dialogflow.v2.UpdateAnswerRecordRequest].
      /// If the value is not empty,
      /// [AnswerFeedback.clicked][google.cloud.dialogflow.v2.AnswerFeedback.clicked]
      /// will be updated to be true.
      ///
      /// [google.cloud.dialogflow.v2.AnswerFeedback.clicked]: <doc:AnswerFeedback/clicked>
      /// [google.cloud.dialogflow.v2.UpdateAnswerRecordRequest]: <doc:UpdateAnswerRecordRequest>
      public var clickedUris: [Swift.String] = []

      /// Initialize a new instance of `KnowledgeSearchFeedback`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = KnowledgeSearchFeedback().with { $0.answerCopied = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dialogflow.v2.AgentAssistantFeedback.KnowledgeSearchFeedback"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Feedback for knowledge assist.
    public struct KnowledgeAssistFeedback: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Whether the suggested answer was copied by the human agent.
      /// If the value is set to be true,
      /// [AnswerFeedback.clicked][google.cloud.dialogflow.v2.AnswerFeedback.clicked]
      /// will be updated to be true.
      ///
      /// [google.cloud.dialogflow.v2.AnswerFeedback.clicked]: <doc:AnswerFeedback/clicked>
      public var answerCopied: Swift.Bool = Swift.Bool()

      /// The URIs clicked by the human agent. The value is appended for each
      /// UpdateAnswerRecordRequest.
      /// If the value is not empty,
      /// [AnswerFeedback.clicked][google.cloud.dialogflow.v2.AnswerFeedback.clicked]
      /// will be updated to be true.
      ///
      /// [google.cloud.dialogflow.v2.AnswerFeedback.clicked]: <doc:AnswerFeedback/clicked>
      public var clickedUris: [Swift.String] = []

      /// Initialize a new instance of `KnowledgeAssistFeedback`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = KnowledgeAssistFeedback().with { $0.answerCopied = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dialogflow.v2.AgentAssistantFeedback.KnowledgeAssistFeedback"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Relevance of an answer.
    public enum AnswerRelevance: Codable, Equatable, Sendable {
      /// Answer relevance unspecified.
      case unspecified
      /// Answer is irrelevant to query.
      case irrelevant
      /// Answer is relevant to query.
      case relevant
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .irrelevant: return 1
        case .relevant: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "ANSWER_RELEVANCE_UNSPECIFIED"
        case .irrelevant: return "IRRELEVANT"
        case .relevant: return "RELEVANT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:AnswerRelevance/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "ANSWER_RELEVANCE_UNSPECIFIED": self = .unspecified
        case "IRRELEVANT": self = .irrelevant
        case "RELEVANT": self = .relevant
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:AnswerRelevance/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .irrelevant
        case 2: self = .relevant
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .irrelevant: return try container.encode(1)
        case .relevant: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Correctness of document.
    public enum DocumentCorrectness: Codable, Equatable, Sendable {
      /// Document correctness unspecified.
      case unspecified
      /// Information in document is incorrect.
      case incorrect
      /// Information in document is correct.
      case correct
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .incorrect: return 1
        case .correct: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DOCUMENT_CORRECTNESS_UNSPECIFIED"
        case .incorrect: return "INCORRECT"
        case .correct: return "CORRECT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DocumentCorrectness/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DOCUMENT_CORRECTNESS_UNSPECIFIED": self = .unspecified
        case "INCORRECT": self = .incorrect
        case "CORRECT": self = .correct
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DocumentCorrectness/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .incorrect
        case 2: self = .correct
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .incorrect: return try container.encode(1)
        case .correct: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Efficiency of document.
    public enum DocumentEfficiency: Codable, Equatable, Sendable {
      /// Document efficiency unspecified.
      case unspecified
      /// Document is inefficient.
      case inefficient
      /// Document is efficient.
      case efficient
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .inefficient: return 1
        case .efficient: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "DOCUMENT_EFFICIENCY_UNSPECIFIED"
        case .inefficient: return "INEFFICIENT"
        case .efficient: return "EFFICIENT"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:DocumentEfficiency/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "DOCUMENT_EFFICIENCY_UNSPECIFIED": self = .unspecified
        case "INEFFICIENT": self = .inefficient
        case "EFFICIENT": self = .efficient
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:DocumentEfficiency/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .inefficient
        case 2: self = .efficient
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .inefficient: return try container.encode(1)
        case .efficient: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.AgentAssistantFeedback"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
