// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if AnswerRecords || Participants
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Represents article answer.
  public struct ArticleAnswer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The article title.
    public var title: Swift.String = Swift.String()

    /// The article URI.
    public var uri: Swift.String = Swift.String()

    /// Article snippets.
    public var snippets: [Swift.String] = []

    /// Article match confidence.
    /// The system's confidence score that this article is a good match for this
    /// conversation, as a value from 0.0 (completely uncertain) to 1.0
    /// (completely certain).
    public var confidence: Swift.Float = Swift.Float()

    /// A map that contains metadata about the answer and the
    /// document from which it originates.
    public var metadata: [Swift.String: Swift.String] = [:]

    /// The name of answer record, in the format of
    /// "projects/<Project ID>/locations/<Location ID>/answerRecords/<Answer Record
    /// ID>"
    public var answerRecord: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `ArticleAnswer`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ArticleAnswer().with { $0.title = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let title = CodingKeys(stringValue: "title")
      static let uri = CodingKeys(stringValue: "uri")
      static let snippets = CodingKeys(stringValue: "snippets")
      static let confidence = CodingKeys(stringValue: "confidence")
      static let metadata = CodingKeys(stringValue: "metadata")
      static let answerRecord = CodingKeys(stringValue: "answerRecord")

      static let _knownKeys: Set<Swift.String> = [
        "title",
        "uri",
        "snippets",
        "confidence",
        "metadata",
        "answerRecord",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .title) {
        self.title = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uri) {
        self.uri = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .snippets) {
        self.snippets = value
      }
      if let value = try container.decodeIfPresent(Swift.Float.self, forKey: .confidence) {
        self.confidence = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .metadata)
      {
        self.metadata = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .answerRecord) {
        self.answerRecord = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.title, forKey: .title)
      try container.encode(self.uri, forKey: .uri)
      try container.encode(self.snippets, forKey: .snippets)
      try container.encode(self.confidence, forKey: .confidence)
      try container.encode(self.metadata, forKey: .metadata)
      try container.encode(self.answerRecord, forKey: .answerRecord)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.ArticleAnswer"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
