// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || GeneratorEvaluations || Generators
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Spec of CES tool that the generator can choose from.
  public struct CesToolSpec: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Format: `projects/<Project ID>/locations/<Location ID>/apps/<app
    /// ID>/tools/<tool ID>`.
    public var cesTool: Swift.String = Swift.String()

    /// Optional. Indicates whether the tool requires human confirmation.
    public var confirmationRequirement: Tool.ConfirmationRequirement =
      Tool.ConfirmationRequirement()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CesToolSpec`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CesToolSpec().with { $0.cesTool = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let cesTool = CodingKeys(stringValue: "cesTool")
      static let confirmationRequirement = CodingKeys(stringValue: "confirmationRequirement")

      static let _knownKeys: Set<Swift.String> = [
        "cesTool",
        "confirmationRequirement",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cesTool) {
        self.cesTool = value
      }
      if let value = try container.decodeIfPresent(
        Tool.ConfirmationRequirement.self, forKey: .confirmationRequirement)
      {
        self.confirmationRequirement = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.cesTool, forKey: .cesTool)
      try container.encode(self.confirmationRequirement, forKey: .confirmationRequirement)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.CesToolSpec"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
