// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Participants || Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Cloud conversation info for easier debugging.
  /// It will get populated in `StreamingDetectIntentResponse` or
  /// `StreamingAnalyzeContentResponse` when the flag `enable_debugging_info` is
  /// set to true in corresponding requests.
  public struct CloudConversationDebuggingInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Number of input audio data chunks in streaming requests.
    public var audioDataChunks: Swift.Int32 = Swift.Int32()

    /// Time offset of the end of speech utterance relative to the
    /// beginning of the first audio chunk.
    public var resultEndTimeOffset: GoogleWKT.Duration? = nil

    /// Duration of first audio chunk.
    public var firstAudioDuration: GoogleWKT.Duration? = nil

    /// Whether client used single utterance mode.
    public var singleUtterance: Swift.Bool = Swift.Bool()

    /// Time offsets of the speech partial results relative to the beginning of
    /// the stream.
    public var speechPartialResultsEndTimes: [GoogleWKT.Duration] = []

    /// Time offsets of the speech final results (is_final=true) relative to the
    /// beginning of the stream.
    public var speechFinalResultsEndTimes: [GoogleWKT.Duration] = []

    /// Total number of partial responses.
    public var partialResponses: Swift.Int32 = Swift.Int32()

    /// Time offset of Speaker ID stream close time relative to the Speech stream
    /// close time in milliseconds. Only meaningful for conversations involving
    /// passive verification.
    public var speakerIdPassiveLatencyMsOffset: Swift.Int32 = Swift.Int32()

    /// Whether a barge-in event is triggered in this request.
    public var bargeinEventTriggered: Swift.Bool = Swift.Bool()

    /// Whether speech uses single utterance mode.
    public var speechSingleUtterance: Swift.Bool = Swift.Bool()

    /// Time offsets of the DTMF partial results relative to the beginning of
    /// the stream.
    public var dtmfPartialResultsTimes: [GoogleWKT.Duration] = []

    /// Time offsets of the DTMF final results relative to the beginning of
    /// the stream.
    public var dtmfFinalResultsTimes: [GoogleWKT.Duration] = []

    /// Time offset of the end-of-single-utterance signal relative to the
    /// beginning of the stream.
    public var singleUtteranceEndTimeOffset: GoogleWKT.Duration? = nil

    /// No speech timeout settings for the stream.
    public var noSpeechTimeout: GoogleWKT.Duration? = nil

    /// Speech endpointing timeout settings for the stream.
    public var endpointingTimeout: GoogleWKT.Duration? = nil

    /// Whether the streaming terminates with an injected text query.
    public var isInputText: Swift.Bool = Swift.Bool()

    /// Client half close time in terms of input audio duration.
    public var clientHalfCloseTimeOffset: GoogleWKT.Duration? = nil

    /// Client half close time in terms of API streaming duration.
    public var clientHalfCloseStreamingTimeOffset: GoogleWKT.Duration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `CloudConversationDebuggingInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CloudConversationDebuggingInfo().with { $0.audioDataChunks = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let audioDataChunks = CodingKeys(stringValue: "audioDataChunks")
      static let resultEndTimeOffset = CodingKeys(stringValue: "resultEndTimeOffset")
      static let firstAudioDuration = CodingKeys(stringValue: "firstAudioDuration")
      static let singleUtterance = CodingKeys(stringValue: "singleUtterance")
      static let speechPartialResultsEndTimes = CodingKeys(
        stringValue: "speechPartialResultsEndTimes")
      static let speechFinalResultsEndTimes = CodingKeys(stringValue: "speechFinalResultsEndTimes")
      static let partialResponses = CodingKeys(stringValue: "partialResponses")
      static let speakerIdPassiveLatencyMsOffset = CodingKeys(
        stringValue: "speakerIdPassiveLatencyMsOffset")
      static let bargeinEventTriggered = CodingKeys(stringValue: "bargeinEventTriggered")
      static let speechSingleUtterance = CodingKeys(stringValue: "speechSingleUtterance")
      static let dtmfPartialResultsTimes = CodingKeys(stringValue: "dtmfPartialResultsTimes")
      static let dtmfFinalResultsTimes = CodingKeys(stringValue: "dtmfFinalResultsTimes")
      static let singleUtteranceEndTimeOffset = CodingKeys(
        stringValue: "singleUtteranceEndTimeOffset")
      static let noSpeechTimeout = CodingKeys(stringValue: "noSpeechTimeout")
      static let endpointingTimeout = CodingKeys(stringValue: "endpointingTimeout")
      static let isInputText = CodingKeys(stringValue: "isInputText")
      static let clientHalfCloseTimeOffset = CodingKeys(stringValue: "clientHalfCloseTimeOffset")
      static let clientHalfCloseStreamingTimeOffset = CodingKeys(
        stringValue: "clientHalfCloseStreamingTimeOffset")

      static let _knownKeys: Set<Swift.String> = [
        "audioDataChunks",
        "resultEndTimeOffset",
        "firstAudioDuration",
        "singleUtterance",
        "speechPartialResultsEndTimes",
        "speechFinalResultsEndTimes",
        "partialResponses",
        "speakerIdPassiveLatencyMsOffset",
        "bargeinEventTriggered",
        "speechSingleUtterance",
        "dtmfPartialResultsTimes",
        "dtmfFinalResultsTimes",
        "singleUtteranceEndTimeOffset",
        "noSpeechTimeout",
        "endpointingTimeout",
        "isInputText",
        "clientHalfCloseTimeOffset",
        "clientHalfCloseStreamingTimeOffset",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .audioDataChunks) {
        self.audioDataChunks = value
      }
      self.resultEndTimeOffset = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .resultEndTimeOffset)
      self.firstAudioDuration = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .firstAudioDuration)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .singleUtterance) {
        self.singleUtterance = value
      }
      if let value = try container.decodeIfPresent(
        [GoogleWKT.Duration].self, forKey: .speechPartialResultsEndTimes)
      {
        self.speechPartialResultsEndTimes = value
      }
      if let value = try container.decodeIfPresent(
        [GoogleWKT.Duration].self, forKey: .speechFinalResultsEndTimes)
      {
        self.speechFinalResultsEndTimes = value
      }
      if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .partialResponses) {
        self.partialResponses = value
      }
      if let value = try container.decodeIfPresent(
        Swift.Int32.self, forKey: .speakerIdPassiveLatencyMsOffset)
      {
        self.speakerIdPassiveLatencyMsOffset = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .bargeinEventTriggered)
      {
        self.bargeinEventTriggered = value
      }
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .speechSingleUtterance)
      {
        self.speechSingleUtterance = value
      }
      if let value = try container.decodeIfPresent(
        [GoogleWKT.Duration].self, forKey: .dtmfPartialResultsTimes)
      {
        self.dtmfPartialResultsTimes = value
      }
      if let value = try container.decodeIfPresent(
        [GoogleWKT.Duration].self, forKey: .dtmfFinalResultsTimes)
      {
        self.dtmfFinalResultsTimes = value
      }
      self.singleUtteranceEndTimeOffset = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .singleUtteranceEndTimeOffset)
      self.noSpeechTimeout = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .noSpeechTimeout)
      self.endpointingTimeout = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .endpointingTimeout)
      if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .isInputText) {
        self.isInputText = value
      }
      self.clientHalfCloseTimeOffset = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .clientHalfCloseTimeOffset)
      self.clientHalfCloseStreamingTimeOffset = try container.decodeIfPresent(
        GoogleWKT.Duration.self, forKey: .clientHalfCloseStreamingTimeOffset)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.audioDataChunks, forKey: .audioDataChunks)
      try container.encodeIfPresent(self.resultEndTimeOffset, forKey: .resultEndTimeOffset)
      try container.encodeIfPresent(self.firstAudioDuration, forKey: .firstAudioDuration)
      try container.encode(self.singleUtterance, forKey: .singleUtterance)
      try container.encode(self.speechPartialResultsEndTimes, forKey: .speechPartialResultsEndTimes)
      try container.encode(self.speechFinalResultsEndTimes, forKey: .speechFinalResultsEndTimes)
      try container.encode(self.partialResponses, forKey: .partialResponses)
      try container.encode(
        self.speakerIdPassiveLatencyMsOffset, forKey: .speakerIdPassiveLatencyMsOffset)
      try container.encode(self.bargeinEventTriggered, forKey: .bargeinEventTriggered)
      try container.encode(self.speechSingleUtterance, forKey: .speechSingleUtterance)
      try container.encode(self.dtmfPartialResultsTimes, forKey: .dtmfPartialResultsTimes)
      try container.encode(self.dtmfFinalResultsTimes, forKey: .dtmfFinalResultsTimes)
      try container.encodeIfPresent(
        self.singleUtteranceEndTimeOffset, forKey: .singleUtteranceEndTimeOffset)
      try container.encodeIfPresent(self.noSpeechTimeout, forKey: .noSpeechTimeout)
      try container.encodeIfPresent(self.endpointingTimeout, forKey: .endpointingTimeout)
      try container.encode(self.isInputText, forKey: .isInputText)
      try container.encodeIfPresent(
        self.clientHalfCloseTimeOffset, forKey: .clientHalfCloseTimeOffset)
      try container.encodeIfPresent(
        self.clientHalfCloseStreamingTimeOffset, forKey: .clientHalfCloseStreamingTimeOffset)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.CloudConversationDebuggingInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
