// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationModels
  import Foundation
  import GoogleCloudWkt

  /// Represents a conversation model.
  public struct ConversationModel: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// ConversationModel resource name. Format:
    /// `projects/<Project ID>/conversationModels/<Conversation Model ID>`
    public var name: Swift.String = Swift.String()

    /// Required. The display name of the model. At most 64 bytes long.
    public var displayName: Swift.String = Swift.String()

    /// Output only. Creation time of this model.
    public var createTime: GoogleCloudWkt.Timestamp? = nil

    /// Required. Datasets used to create model.
    public var datasets: [InputDataset] = []

    /// Output only. State of the model. A model can only serve prediction requests
    /// after it gets deployed.
    public var state: ConversationModel.State = ConversationModel.State()

    /// Language code for the conversation model. If not specified, the language
    /// is en-US. Language at ConversationModel should be set for all non en-us
    /// languages.
    /// This should be a [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)
    /// language tag. Example: "en-US".
    public var languageCode: Swift.String = Swift.String()

    /// Output only. A read only boolean field reflecting Zone Separation
    /// status of the model.
    public var satisfiesPzs: Swift.Bool? = nil

    /// Output only. A read only boolean field reflecting Zone Isolation status
    /// of the model.
    public var satisfiesPzi: Swift.Bool? = nil

    /// Required.
    /// The model metadata that is specific to the problem type.
    /// Must match the metadata type of the dataset used to train the model.
    public var modelMetadata: OneOf_ModelMetadata? = nil

    /// Initialize a new instance of `ConversationModel`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConversationModel().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case name = "name"
      case displayName = "displayName"
      case createTime = "createTime"
      case datasets = "datasets"
      case state = "state"
      case languageCode = "languageCode"
      case articleSuggestionModelMetadata = "articleSuggestionModelMetadata"
      case smartReplyModelMetadata = "smartReplyModelMetadata"
      case satisfiesPzs = "satisfiesPzs"
      case satisfiesPzi = "satisfiesPzi"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.name = try container.decode(Swift.String.self, forKey: .name)
      self.displayName = try container.decode(Swift.String.self, forKey: .displayName)
      self.createTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp.self, forKey: .createTime)
      self.datasets = try container.decode([InputDataset].self, forKey: .datasets)
      self.state = try container.decode(ConversationModel.State.self, forKey: .state)
      self.languageCode = try container.decode(Swift.String.self, forKey: .languageCode)
      self.satisfiesPzs = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzs)
      self.satisfiesPzi = try container.decodeIfPresent(Swift.Bool.self, forKey: .satisfiesPzi)

      var modelMetadata: OneOf_ModelMetadata? = nil
      let modelMetadataCheckAndSet = {
        if modelMetadata != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'modelMetadata'"))
        }
        modelMetadata = $0
      }
      if let articleSuggestionModelMetadata = try container.decodeIfPresent(
        ArticleSuggestionModelMetadata?.self, forKey: .articleSuggestionModelMetadata)
      {
        try modelMetadataCheckAndSet(
          .articleSuggestionModelMetadata(articleSuggestionModelMetadata))
      }
      if let smartReplyModelMetadata = try container.decodeIfPresent(
        SmartReplyModelMetadata?.self, forKey: .smartReplyModelMetadata)
      {
        try modelMetadataCheckAndSet(.smartReplyModelMetadata(smartReplyModelMetadata))
      }
      self.modelMetadata = modelMetadata
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.createTime, forKey: .createTime)
      try container.encode(self.datasets, forKey: .datasets)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.languageCode, forKey: .languageCode)
      try container.encode(self.satisfiesPzs, forKey: .satisfiesPzs)
      try container.encode(self.satisfiesPzi, forKey: .satisfiesPzi)

      if let choice = self.modelMetadata {
        switch choice {
        case .articleSuggestionModelMetadata(let value):
          try container.encode(value, forKey: .articleSuggestionModelMetadata)
        case .smartReplyModelMetadata(let value):
          try container.encode(value, forKey: .smartReplyModelMetadata)
        }
      }
    }

    /// State of the model.
    public enum State: Codable, Equatable, Sendable {
      /// Should not be used, an un-set enum has this value by default.
      case unspecified
      /// Model being created.
      case creating
      /// Model is not deployed but ready to deploy.
      case undeployed
      /// Model is deploying.
      case deploying
      /// Model is deployed and ready to use.
      case deployed
      /// Model is undeploying.
      case undeploying
      /// Model is deleting.
      case deleting
      /// Model is in error state. Not ready to deploy and use.
      case failed
      /// Model is being created but the training has not started,
      /// The model may remain in this state until there is enough capacity to
      /// start training.
      case pending
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .creating: return 1
        case .undeployed: return 2
        case .deploying: return 3
        case .deployed: return 4
        case .undeploying: return 5
        case .deleting: return 6
        case .failed: return 7
        case .pending: return 8
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .creating: return "CREATING"
        case .undeployed: return "UNDEPLOYED"
        case .deploying: return "DEPLOYING"
        case .deployed: return "DEPLOYED"
        case .undeploying: return "UNDEPLOYING"
        case .deleting: return "DELETING"
        case .failed: return "FAILED"
        case .pending: return "PENDING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "CREATING": self = .creating
        case "UNDEPLOYED": self = .undeployed
        case "DEPLOYING": self = .deploying
        case "DEPLOYED": self = .deployed
        case "UNDEPLOYING": self = .undeploying
        case "DELETING": self = .deleting
        case "FAILED": self = .failed
        case "PENDING": self = .pending
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .creating
        case 2: self = .undeployed
        case 3: self = .deploying
        case 4: self = .deployed
        case 5: self = .undeploying
        case 6: self = .deleting
        case 7: self = .failed
        case 8: self = .pending
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .creating: return try container.encode(1)
        case .undeployed: return try container.encode(2)
        case .deploying: return try container.encode(3)
        case .deployed: return try container.encode(4)
        case .undeploying: return try container.encode(5)
        case .deleting: return try container.encode(6)
        case .failed: return try container.encode(7)
        case .pending: return try container.encode(8)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Model type.
    public enum ModelType: Codable, Equatable, Sendable {
      /// ModelType unspecified.
      case unspecified
      /// ModelType smart reply dual encoder model.
      case smartReplyDualEncoderModel
      /// ModelType smart reply bert model.
      case smartReplyBertModel
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .smartReplyDualEncoderModel: return 2
        case .smartReplyBertModel: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "MODEL_TYPE_UNSPECIFIED"
        case .smartReplyDualEncoderModel: return "SMART_REPLY_DUAL_ENCODER_MODEL"
        case .smartReplyBertModel: return "SMART_REPLY_BERT_MODEL"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "MODEL_TYPE_UNSPECIFIED": self = .unspecified
        case "SMART_REPLY_DUAL_ENCODER_MODEL": self = .smartReplyDualEncoderModel
        case "SMART_REPLY_BERT_MODEL": self = .smartReplyBertModel
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 2: self = .smartReplyDualEncoderModel
        case 6: self = .smartReplyBertModel
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .smartReplyDualEncoderModel: return try container.encode(2)
        case .smartReplyBertModel: return try container.encode(6)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Required.
    /// The model metadata that is specific to the problem type.
    /// Must match the metadata type of the dataset used to train the model.
    public enum OneOf_ModelMetadata: Codable, Equatable, Sendable {
      /// Metadata for article suggestion models.
      indirect case articleSuggestionModelMetadata(ArticleSuggestionModelMetadata?)
      /// Metadata for smart reply models.
      indirect case smartReplyModelMetadata(SmartReplyModelMetadata?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.ConversationModel"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
