// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleCloudGax

  /// Service for managing
  /// [Conversations][google.cloud.dialogflow.v2.Conversation].
  ///
  /// [google.cloud.dialogflow.v2.Conversation]: <doc:Conversation>
  ///
  /// @Snippet(path: "ConversationsQuickstart")
  public class ConversationsClient: Clients.ConversationsProtocol {
    let inner: any Clients.ConversationsStub

    /// Creates a new `ConversationsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.ConversationsStub = try Clients.ConversationsTransport(options)
      inner = Clients.ConversationsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.ConversationsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Creates a new conversation. Conversations are auto-completed after 24
    /// hours.
    ///
    /// Conversation Lifecycle:
    /// There are two stages during a conversation: Automated Agent Stage and
    /// Assist Stage.
    ///
    /// For Automated Agent Stage, there will be a dialogflow agent responding to
    /// user queries.
    ///
    /// For Assist Stage, there's no dialogflow agent responding to user queries.
    /// But we will provide suggestions which are generated from conversation.
    ///
    /// If
    /// [Conversation.conversation_profile][google.cloud.dialogflow.v2.Conversation.conversation_profile]
    /// is configured for a dialogflow agent, conversation will start from
    /// `Automated Agent Stage`, otherwise, it will start from `Assist Stage`. And
    /// during `Automated Agent Stage`, once an
    /// [Intent][google.cloud.dialogflow.v2.Intent] with
    /// [Intent.live_agent_handoff][google.cloud.dialogflow.v2.Intent.live_agent_handoff]
    /// is triggered, conversation will transfer to Assist Stage.
    ///
    /// [google.cloud.dialogflow.v2.Conversation.conversation_profile]: <doc:Conversation/conversationProfile>
    /// [google.cloud.dialogflow.v2.Intent]: <doc:Intent>
    /// [google.cloud.dialogflow.v2.Intent.live_agent_handoff]: <doc:Intent/liveAgentHandoff>
    ///
    /// @Snippet(path: "Conversations_CreateConversation")
    public func createConversation(
      request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      try await self.inner.createConversation(request: request, options: options)
    }

    /// Returns the list of all conversations in the specified project.
    ///
    /// @Snippet(path: "Conversations_ListConversations")
    public func listConversations(
      request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListConversationsResponse {
      try await self.inner.listConversations(request: request, options: options)
    }

    /// Returns the list of all conversations in the specified project.
    ///
    /// @Snippet(path: "Conversations_ListConversations")
    public func listConversations(
      byItem: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Conversation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListConversationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listConversations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Retrieves the specific conversation.
    ///
    /// @Snippet(path: "Conversations_GetConversation")
    public func getConversation(
      request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      try await self.inner.getConversation(request: request, options: options)
    }

    /// Completes the specified conversation. Finished conversations are purged
    /// from the database after 30 days.
    ///
    /// @Snippet(path: "Conversations_CompleteConversation")
    public func completeConversation(
      request: CompleteConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      try await self.inner.completeConversation(request: request, options: options)
    }

    /// Data ingestion API.
    /// Ingests context references for an existing conversation.
    ///
    /// @Snippet(path: "Conversations_IngestContextReferences")
    public func ingestContextReferences(
      request: IngestContextReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.IngestContextReferencesResponse {
      try await self.inner.ingestContextReferences(request: request, options: options)
    }

    /// Lists messages that belong to a given conversation.
    /// `messages` are ordered by `create_time` in descending order. To fetch
    /// updates without duplication, send request with filter
    /// `create_time_epoch_microseconds >
    /// [first item's create_time of previous request]` and empty page_token.
    ///
    /// @Snippet(path: "Conversations_ListMessages")
    public func listMessages(
      request: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListMessagesResponse {
      try await self.inner.listMessages(request: request, options: options)
    }

    /// Lists messages that belong to a given conversation.
    /// `messages` are ordered by `create_time` in descending order. To fetch
    /// updates without duplication, send request with filter
    /// `create_time_epoch_microseconds >
    /// [first item's create_time of previous request]` and empty page_token.
    ///
    /// @Snippet(path: "Conversations_ListMessages")
    public func listMessages(
      byItem: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Message, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListMessagesResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listMessages(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Suggests summary for a conversation based on specific historical messages.
    /// The range of the messages to be used for summary can be specified in the
    /// request.
    ///
    /// @Snippet(path: "Conversations_SuggestConversationSummary")
    public func suggestConversationSummary(
      request: SuggestConversationSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse {
      try await self.inner.suggestConversationSummary(request: request, options: options)
    }

    /// Generates and returns a summary for a conversation that does not have a
    /// resource created for it.
    ///
    /// @Snippet(path: "Conversations_GenerateStatelessSummary")
    public func generateStatelessSummary(
      request: GenerateStatelessSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSummaryResponse {
      try await self.inner.generateStatelessSummary(request: request, options: options)
    }

    /// Generates and returns a suggestion for a conversation that does not have a
    /// resource created for it.
    ///
    /// @Snippet(path: "Conversations_GenerateStatelessSuggestion")
    public func generateStatelessSuggestion(
      request: GenerateStatelessSuggestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSuggestionResponse {
      try await self.inner.generateStatelessSuggestion(request: request, options: options)
    }

    /// Get answers for the given query based on knowledge documents.
    ///
    /// @Snippet(path: "Conversations_SearchKnowledge")
    public func searchKnowledge(
      request: SearchKnowledgeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SearchKnowledgeResponse {
      try await self.inner.searchKnowledge(request: request, options: options)
    }

    /// Generates all the suggestions using generators configured in the
    /// conversation profile. A generator is used only if its trigger event is
    /// matched.
    ///
    /// @Snippet(path: "Conversations_GenerateSuggestions")
    public func generateSuggestions(
      request: GenerateSuggestionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse {
      try await self.inner.generateSuggestions(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Conversations_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Conversations_ListLocations")
    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "Conversations_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Conversations_ListOperations")
    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Conversations_ListOperations")
    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Conversations_GetOperation")
    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
    ///
    /// @Snippet(path: "Conversations_CancelOperation")
    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `ConversationsClient`.
    ///
    /// To mock `ConversationsClient` change your functions to receive
    /// `some ConversationsProtocol` or `any ConversationsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol ConversationsProtocol {
      /// See `ConversationsClient.createConversation`.
      func createConversation(request: CreateConversationRequest) async throws
        -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.createConversation`.
      func createConversation(
        parent: Swift.String,
        conversation: Conversation?,
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.listConversations`.
      func listConversations(request: ListConversationsRequest) async throws
        -> GoogleCloudDialogflowV2.ListConversationsResponse

      /// See `ConversationsClient.listConversations`.
      func listConversations(
        byItem: ListConversationsRequest
      ) throws -> any AsyncSequence<Conversation, Swift.Error>

      /// See `ConversationsClient.listConversations`.
      func listConversations(
        parent: Swift.String,
      ) throws -> any AsyncSequence<Conversation, Swift.Error>

      /// See `ConversationsClient.getConversation`.
      func getConversation(request: GetConversationRequest) async throws
        -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.getConversation`.
      func getConversation(
        name: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.completeConversation`.
      func completeConversation(request: CompleteConversationRequest) async throws
        -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.completeConversation`.
      func completeConversation(
        name: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.ingestContextReferences`.
      func ingestContextReferences(request: IngestContextReferencesRequest) async throws
        -> GoogleCloudDialogflowV2.IngestContextReferencesResponse

      /// See `ConversationsClient.ingestContextReferences`.
      func ingestContextReferences(
        conversation: Swift.String,
        contextReferences: [Swift.String: Conversation.ContextReference],
      ) async throws -> GoogleCloudDialogflowV2.IngestContextReferencesResponse

      /// See `ConversationsClient.listMessages`.
      func listMessages(request: ListMessagesRequest) async throws
        -> GoogleCloudDialogflowV2.ListMessagesResponse

      /// See `ConversationsClient.listMessages`.
      func listMessages(
        byItem: ListMessagesRequest
      ) throws -> any AsyncSequence<Message, Swift.Error>

      /// See `ConversationsClient.listMessages`.
      func listMessages(
        parent: Swift.String,
      ) throws -> any AsyncSequence<Message, Swift.Error>

      /// See `ConversationsClient.suggestConversationSummary`.
      func suggestConversationSummary(request: SuggestConversationSummaryRequest) async throws
        -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse

      /// See `ConversationsClient.suggestConversationSummary`.
      func suggestConversationSummary(
        conversation: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse

      /// See `ConversationsClient.generateStatelessSummary`.
      func generateStatelessSummary(request: GenerateStatelessSummaryRequest) async throws
        -> GoogleCloudDialogflowV2.GenerateStatelessSummaryResponse

      /// See `ConversationsClient.generateStatelessSuggestion`.
      func generateStatelessSuggestion(request: GenerateStatelessSuggestionRequest) async throws
        -> GoogleCloudDialogflowV2.GenerateStatelessSuggestionResponse

      /// See `ConversationsClient.searchKnowledge`.
      func searchKnowledge(request: SearchKnowledgeRequest) async throws
        -> GoogleCloudDialogflowV2.SearchKnowledgeResponse

      /// See `ConversationsClient.generateSuggestions`.
      func generateSuggestions(request: GenerateSuggestionsRequest) async throws
        -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse

      /// See `ConversationsClient.generateSuggestions`.
      func generateSuggestions(
        conversation: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse

      /// See `ConversationsClient.listLocations`.
      func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
        -> GoogleCloudLocation.ListLocationsResponse

      /// See `ConversationsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `ConversationsClient.getLocation`.
      func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
        -> GoogleCloudLocation.Location

      /// See `ConversationsClient.listOperations`.
      func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
        -> GoogleLongRunning.ListOperationsResponse

      /// See `ConversationsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `ConversationsClient.listOperations`.
      func listOperations(
        name: Swift.String,
        filter: Swift.String,
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `ConversationsClient.cancelOperation`.
      func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

      /// See `ConversationsClient.cancelOperation`.
      func cancelOperation(
        name: Swift.String,
      ) async throws

      /// See `ConversationsClient.createConversation`.
      func createConversation(
        request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.listConversations`.
      func listConversations(
        request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListConversationsResponse

      /// See `ConversationsClient.listConversations`.
      func listConversations(
        byItem: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Conversation, Swift.Error>

      /// See `ConversationsClient.getConversation`.
      func getConversation(
        request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.completeConversation`.
      func completeConversation(
        request: CompleteConversationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Conversation

      /// See `ConversationsClient.ingestContextReferences`.
      func ingestContextReferences(
        request: IngestContextReferencesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.IngestContextReferencesResponse

      /// See `ConversationsClient.listMessages`.
      func listMessages(
        request: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListMessagesResponse

      /// See `ConversationsClient.listMessages`.
      func listMessages(
        byItem: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Message, Swift.Error>

      /// See `ConversationsClient.suggestConversationSummary`.
      func suggestConversationSummary(
        request: SuggestConversationSummaryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse

      /// See `ConversationsClient.generateStatelessSummary`.
      func generateStatelessSummary(
        request: GenerateStatelessSummaryRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSummaryResponse

      /// See `ConversationsClient.generateStatelessSuggestion`.
      func generateStatelessSuggestion(
        request: GenerateStatelessSuggestionRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSuggestionResponse

      /// See `ConversationsClient.searchKnowledge`.
      func searchKnowledge(
        request: SearchKnowledgeRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SearchKnowledgeResponse

      /// See `ConversationsClient.generateSuggestions`.
      func generateSuggestions(
        request: GenerateSuggestionsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse

      /// See `ConversationsClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `ConversationsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `ConversationsClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `ConversationsClient.listOperations`.
      func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse

      /// See `ConversationsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

      /// See `ConversationsClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.ConversationsProtocol {
    public func createConversation(request: CreateConversationRequest) async throws
      -> GoogleCloudDialogflowV2.Conversation
    {
      try await self.createConversation(request: request, options: .init())
    }

    public func createConversation(
      request: CreateConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func createConversation(
      parent: Swift.String,
      conversation: Conversation?,
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      let request = CreateConversationRequest().with {
        $0.parent = parent
        $0.conversation = conversation
      }
      return try await self.createConversation(request: request)
    }

    public func listConversations(request: ListConversationsRequest) async throws
      -> GoogleCloudDialogflowV2.ListConversationsResponse
    {
      try await self.listConversations(request: request, options: .init())
    }

    public func listConversations(
      request: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListConversationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listConversations(
      byItem: ListConversationsRequest
    ) throws -> any AsyncSequence<Conversation, Swift.Error> {
      try self.listConversations(byItem: byItem, options: .init())
    }

    public func listConversations(
      byItem: ListConversationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Conversation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListConversationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listConversations(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Conversation, Swift.Error> {
      let request = ListConversationsRequest().with {
        $0.parent = parent
      }
      return try self.listConversations(byItem: request)
    }

    public func getConversation(request: GetConversationRequest) async throws
      -> GoogleCloudDialogflowV2.Conversation
    {
      try await self.getConversation(request: request, options: .init())
    }

    public func getConversation(
      request: GetConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getConversation(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      let request = GetConversationRequest().with {
        $0.name = name
      }
      return try await self.getConversation(request: request)
    }

    public func completeConversation(request: CompleteConversationRequest) async throws
      -> GoogleCloudDialogflowV2.Conversation
    {
      try await self.completeConversation(request: request, options: .init())
    }

    public func completeConversation(
      request: CompleteConversationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func completeConversation(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.Conversation {
      let request = CompleteConversationRequest().with {
        $0.name = name
      }
      return try await self.completeConversation(request: request)
    }

    public func ingestContextReferences(request: IngestContextReferencesRequest) async throws
      -> GoogleCloudDialogflowV2.IngestContextReferencesResponse
    {
      try await self.ingestContextReferences(request: request, options: .init())
    }

    public func ingestContextReferences(
      request: IngestContextReferencesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.IngestContextReferencesResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func ingestContextReferences(
      conversation: Swift.String,
      contextReferences: [Swift.String: Conversation.ContextReference],
    ) async throws -> GoogleCloudDialogflowV2.IngestContextReferencesResponse {
      let request = IngestContextReferencesRequest().with {
        $0.conversation = conversation
        $0.contextReferences = contextReferences
      }
      return try await self.ingestContextReferences(request: request)
    }

    public func listMessages(request: ListMessagesRequest) async throws
      -> GoogleCloudDialogflowV2.ListMessagesResponse
    {
      try await self.listMessages(request: request, options: .init())
    }

    public func listMessages(
      request: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListMessagesResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listMessages(
      byItem: ListMessagesRequest
    ) throws -> any AsyncSequence<Message, Swift.Error> {
      try self.listMessages(byItem: byItem, options: .init())
    }

    public func listMessages(
      byItem: ListMessagesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Message, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListMessagesResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listMessages(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Message, Swift.Error> {
      let request = ListMessagesRequest().with {
        $0.parent = parent
      }
      return try self.listMessages(byItem: request)
    }

    public func suggestConversationSummary(request: SuggestConversationSummaryRequest) async throws
      -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse
    {
      try await self.suggestConversationSummary(request: request, options: .init())
    }

    public func suggestConversationSummary(
      request: SuggestConversationSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func suggestConversationSummary(
      conversation: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.SuggestConversationSummaryResponse {
      let request = SuggestConversationSummaryRequest().with {
        $0.conversation = conversation
      }
      return try await self.suggestConversationSummary(request: request)
    }

    public func generateStatelessSummary(request: GenerateStatelessSummaryRequest) async throws
      -> GoogleCloudDialogflowV2.GenerateStatelessSummaryResponse
    {
      try await self.generateStatelessSummary(request: request, options: .init())
    }

    public func generateStatelessSummary(
      request: GenerateStatelessSummaryRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSummaryResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func generateStatelessSuggestion(request: GenerateStatelessSuggestionRequest)
      async throws -> GoogleCloudDialogflowV2.GenerateStatelessSuggestionResponse
    {
      try await self.generateStatelessSuggestion(request: request, options: .init())
    }

    public func generateStatelessSuggestion(
      request: GenerateStatelessSuggestionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateStatelessSuggestionResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func searchKnowledge(request: SearchKnowledgeRequest) async throws
      -> GoogleCloudDialogflowV2.SearchKnowledgeResponse
    {
      try await self.searchKnowledge(request: request, options: .init())
    }

    public func searchKnowledge(
      request: SearchKnowledgeRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SearchKnowledgeResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func generateSuggestions(request: GenerateSuggestionsRequest) async throws
      -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse
    {
      try await self.generateSuggestions(request: request, options: .init())
    }

    public func generateSuggestions(
      request: GenerateSuggestionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func generateSuggestions(
      conversation: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.GenerateSuggestionsResponse {
      let request = GenerateSuggestionsRequest().with {
        $0.conversation = conversation
      }
      return try await self.generateSuggestions(request: request)
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      try self.listLocations(byItem: byItem, options: .init())
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      try self.listOperations(byItem: byItem, options: .init())
    }

    public func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
      let request = GoogleLongRunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return try self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
      -> GoogleLongRunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongRunning.Operation {
      let request = GoogleLongRunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongRunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#endif
