// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationDatasets
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Represents a conversation dataset that a user imports raw data into.
  /// The data inside ConversationDataset can not be changed after
  /// ImportConversationData finishes (and calling ImportConversationData on a
  /// dataset that already has data is not allowed).
  public struct ConversationDataset: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Output only. ConversationDataset resource name. Format:
    /// `projects/<Project ID>/locations/<Location
    /// ID>/conversationDatasets/<Conversation Dataset ID>`
    public var name: Swift.String = Swift.String()

    /// Required. The display name of the dataset. Maximum of 64 bytes.
    public var displayName: Swift.String = Swift.String()

    /// Optional. The description of the dataset. Maximum of 10000 bytes.
    public var description: Swift.String = Swift.String()

    /// Output only. Creation time of this dataset.
    public var createTime: GoogleCloudWKT.Timestamp? = nil

    /// Output only. Input configurations set during conversation data import.
    public var inputConfig: InputConfig? = nil

    /// Output only. Metadata set during conversation data import.
    public var conversationInfo: ConversationInfo? = nil

    /// Output only. The number of conversations this conversation dataset
    /// contains.
    public var conversationCount: Swift.Int64 = Swift.Int64()

    /// Output only. A read only boolean field reflecting Zone Isolation status of
    /// the dataset.
    public var satisfiesPzi: Swift.Bool? = nil

    /// Output only. A read only boolean field reflecting Zone Separation status of
    /// the dataset.
    public var satisfiesPzs: Swift.Bool? = nil

    /// Initialize a new instance of `ConversationDataset`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConversationDataset().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.ConversationDataset"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
