// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationModels
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleLongRunning
  import GoogleRpc
  import GoogleWKT
  import GoogleGax
  import struct Logging.Logger

  extension Clients {
    final class ConversationModelsLogging: ConversationModelsStub {
      let inner: any ConversationModelsStub
      let logger: Logger

      public init(_ inner: any ConversationModelsStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dialogflow-v2"
        logger[metadataKey: "gcp.client.service"] = "dialogflow"
        logger[metadataKey: "gcp.experimental.swift.client"] = "ConversationModels"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func createConversationModel(
        request: CreateConversationModelRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "createConversationModel",
          action: {
            (r: CreateConversationModelRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.createConversationModel(request: r, options: o)
          })
      }

      public func getConversationModel(
        request: GetConversationModelRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ConversationModel {
        try await self._intercept(
          request: request,
          options: options,
          name: "getConversationModel",
          action: {
            (r: GetConversationModelRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ConversationModel
            in
            return try await self.inner.getConversationModel(request: r, options: o)
          })
      }

      public func listConversationModels(
        request: ListConversationModelsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListConversationModelsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listConversationModels",
          action: {
            (r: ListConversationModelsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ListConversationModelsResponse
            in
            return try await self.inner.listConversationModels(request: r, options: o)
          })
      }

      public func deleteConversationModel(
        request: DeleteConversationModelRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteConversationModel",
          action: {
            (r: DeleteConversationModelRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deleteConversationModel(request: r, options: o)
          })
      }

      public func deployConversationModel(
        request: DeployConversationModelRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "deployConversationModel",
          action: {
            (r: DeployConversationModelRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.deployConversationModel(request: r, options: o)
          })
      }

      public func undeployConversationModel(
        request: UndeployConversationModelRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "undeployConversationModel",
          action: {
            (r: UndeployConversationModelRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.undeployConversationModel(request: r, options: o)
          })
      }

      public func getConversationModelEvaluation(
        request: GetConversationModelEvaluationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ConversationModelEvaluation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getConversationModelEvaluation",
          action: {
            (r: GetConversationModelEvaluationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ConversationModelEvaluation
            in
            return try await self.inner.getConversationModelEvaluation(request: r, options: o)
          })
      }

      public func listConversationModelEvaluations(
        request: ListConversationModelEvaluationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListConversationModelEvaluationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listConversationModelEvaluations",
          action: {
            (r: ListConversationModelEvaluationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ListConversationModelEvaluationsResponse
            in
            return try await self.inner.listConversationModelEvaluations(request: r, options: o)
          })
      }

      public func createConversationModelEvaluation(
        request: CreateConversationModelEvaluationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "createConversationModelEvaluation",
          action: {
            (r: CreateConversationModelEvaluationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.createConversationModelEvaluation(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listLocations",
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          name: "getLocation",
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listOperations",
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancelOperation",
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
