// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Contexts
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The request message for
  /// [Contexts.CreateContext][google.cloud.dialogflow.v2.Contexts.CreateContext].
  ///
  /// [google.cloud.dialogflow.v2.Contexts.CreateContext]: <doc:ContextsClient/createContext(request:options:)>
  public struct CreateContextRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. The session to create a context for.
    /// Format: `projects/<Project ID>/agent/sessions/<Session ID>` or
    /// `projects/<Project ID>/agent/environments/<Environment ID>/users/<User
    /// ID>/sessions/<Session ID>`.
    /// If `Environment ID` is not specified, we assume default 'draft'
    /// environment. If `User ID` is not specified, we assume default '-' user.
    public var parent: Swift.String = Swift.String()

    /// Required. The context to create.
    public var context: Context? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `CreateContextRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = CreateContextRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let context = CodingKeys(stringValue: "context")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "context",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }
      self.context = try container.decodeIfPresent(Context.self, forKey: .context)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encodeIfPresent(self.context, forKey: .context)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.CreateContextRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
