// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || Participants
  import Foundation

  /// Response reason from datastore which indicates data serving status or
  /// answer quality degradation.
  public enum DatastoreResponseReason: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// No specific response reason from datastore.
    case `none`
    /// Search is blocked due to out of quota.
    case searchOutOfQuota
    /// Search returns empty results.
    case searchEmptyResults
    /// Generative AI is disabled.
    case answerGenerationGenAiDisabled
    /// Answer generation is blocked due to out of quota.
    case answerGenerationOutOfQuota
    /// Answer generation encounters an error.
    case answerGenerationError
    /// Answer generation does not have enough information to generate answer.
    case answerGenerationNotEnoughInfo
    /// Answer generation is blocked by RAI (Responsible AI) failure.
    case answerGenerationRaiFailed
    /// Answer generation is not grounded on reliable sources.
    case answerGenerationNotGrounded
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .searchOutOfQuota: return 2
      case .searchEmptyResults: return 3
      case .answerGenerationGenAiDisabled: return 4
      case .answerGenerationOutOfQuota: return 5
      case .answerGenerationError: return 6
      case .answerGenerationNotEnoughInfo: return 7
      case .answerGenerationRaiFailed: return 8
      case .answerGenerationNotGrounded: return 9
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "DATASTORE_RESPONSE_REASON_UNSPECIFIED"
      case .`none`: return "NONE"
      case .searchOutOfQuota: return "SEARCH_OUT_OF_QUOTA"
      case .searchEmptyResults: return "SEARCH_EMPTY_RESULTS"
      case .answerGenerationGenAiDisabled: return "ANSWER_GENERATION_GEN_AI_DISABLED"
      case .answerGenerationOutOfQuota: return "ANSWER_GENERATION_OUT_OF_QUOTA"
      case .answerGenerationError: return "ANSWER_GENERATION_ERROR"
      case .answerGenerationNotEnoughInfo: return "ANSWER_GENERATION_NOT_ENOUGH_INFO"
      case .answerGenerationRaiFailed: return "ANSWER_GENERATION_RAI_FAILED"
      case .answerGenerationNotGrounded: return "ANSWER_GENERATION_NOT_GROUNDED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "DATASTORE_RESPONSE_REASON_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "SEARCH_OUT_OF_QUOTA": self = .searchOutOfQuota
      case "SEARCH_EMPTY_RESULTS": self = .searchEmptyResults
      case "ANSWER_GENERATION_GEN_AI_DISABLED": self = .answerGenerationGenAiDisabled
      case "ANSWER_GENERATION_OUT_OF_QUOTA": self = .answerGenerationOutOfQuota
      case "ANSWER_GENERATION_ERROR": self = .answerGenerationError
      case "ANSWER_GENERATION_NOT_ENOUGH_INFO": self = .answerGenerationNotEnoughInfo
      case "ANSWER_GENERATION_RAI_FAILED": self = .answerGenerationRaiFailed
      case "ANSWER_GENERATION_NOT_GROUNDED": self = .answerGenerationNotGrounded
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .searchOutOfQuota
      case 3: self = .searchEmptyResults
      case 4: self = .answerGenerationGenAiDisabled
      case 5: self = .answerGenerationOutOfQuota
      case 6: self = .answerGenerationError
      case 7: self = .answerGenerationNotEnoughInfo
      case 8: self = .answerGenerationRaiFailed
      case 9: self = .answerGenerationNotGrounded
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`none`: return try container.encode(1)
      case .searchOutOfQuota: return try container.encode(2)
      case .searchEmptyResults: return try container.encode(3)
      case .answerGenerationGenAiDisabled: return try container.encode(4)
      case .answerGenerationOutOfQuota: return try container.encode(5)
      case .answerGenerationError: return try container.encode(6)
      case .answerGenerationNotEnoughInfo: return try container.encode(7)
      case .answerGenerationRaiFailed: return try container.encode(8)
      case .answerGenerationNotGrounded: return try container.encode(9)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }
#endif
