// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Participants || Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt
  import GoogleRpc

  /// The message returned from the [DetectIntent][] method.
  public struct DetectIntentResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The unique identifier of the response. It can be used to
    /// locate a response in the training example set or for reporting issues.
    public var responseId: Swift.String = Swift.String()

    /// The selected results of the conversational query or event processing.
    /// See `alternative_query_results` for additional potential results.
    public var queryResult: QueryResult? = nil

    /// Specifies the status of the webhook request.
    public var webhookStatus: GoogleRpc.Status? = nil

    /// The audio data bytes encoded as specified in the request.
    /// Note: The output audio is generated based on the values of default platform
    /// text responses found in the `query_result.fulfillment_messages` field. If
    /// multiple default text responses exist, they will be concatenated when
    /// generating audio. If no default platform text responses exist, the
    /// generated audio content will be empty.
    ///
    /// In some scenarios, multiple output audio fields may be present in the
    /// response structure. In these cases, only the top-most-level audio output
    /// has content.
    public var outputAudio: Foundation.Data = Foundation.Data()

    /// The config used by the speech synthesizer to generate the output audio.
    public var outputAudioConfig: OutputAudioConfig? = nil

    /// Initialize a new instance of `DetectIntentResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DetectIntentResponse().with { $0.responseId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.DetectIntentResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
