// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Environments
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleGax
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// The response message for
  /// [Environments.GetEnvironmentHistory][google.cloud.dialogflow.v2.Environments.GetEnvironmentHistory].
  ///
  /// [google.cloud.dialogflow.v2.Environments.GetEnvironmentHistory]: <doc:EnvironmentsClient/getEnvironmentHistory(request:options:)>
  public struct EnvironmentHistory: Codable, Equatable, GoogleWKT._AnyPackable,
    GoogleGax._PaginatedResponse,
    Sendable
  {
    /// Output only. The name of the environment this history is for.
    /// Supported formats:
    ///
    /// - `projects/<Project ID>/agent/environments/<Environment ID>`
    /// - `projects/<Project ID>/locations/<Location
    ///    ID>/agent/environments/<Environment ID>`
    ///
    /// The environment ID for the default environment is `-`.
    public var parent: Swift.String = Swift.String()

    /// Output only. The list of agent environments. There will be a maximum number
    /// of items returned based on the page_size field in the request.
    public var entries: [EnvironmentHistory.Entry] = []

    /// Output only. Token to retrieve the next page of results, or empty if there
    /// are no more results in the list.
    public var nextPageToken: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `EnvironmentHistory`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EnvironmentHistory().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let entries = CodingKeys(stringValue: "entries")
      static let nextPageToken = CodingKeys(stringValue: "nextPageToken")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "entries",
        "nextPageToken",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }
      if let value = try container.decodeIfPresent(
        [EnvironmentHistory.Entry].self, forKey: .entries)
      {
        self.entries = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nextPageToken) {
        self.nextPageToken = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.entries, forKey: .entries)
      try container.encode(self.nextPageToken, forKey: .nextPageToken)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Represents an environment history entry.
    public struct Entry: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The agent version loaded into this environment history entry.
      public var agentVersion: Swift.String = Swift.String()

      /// The developer-provided description for this environment history entry.
      public var description: Swift.String = Swift.String()

      /// The creation time of this environment history entry.
      public var createTime: GoogleWKT.Timestamp? = nil

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Entry`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Entry().with { $0.agentVersion = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let agentVersion = CodingKeys(stringValue: "agentVersion")
        static let description = CodingKeys(stringValue: "description")
        static let createTime = CodingKeys(stringValue: "createTime")

        static let _knownKeys: Set<Swift.String> = [
          "agentVersion",
          "description",
          "createTime",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .agentVersion) {
          self.agentVersion = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
          self.description = value
        }
        self.createTime = try container.decodeIfPresent(
          GoogleWKT.Timestamp.self, forKey: .createTime)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.agentVersion, forKey: .agentVersion)
        try container.encode(self.description, forKey: .description)
        try container.encodeIfPresent(self.createTime, forKey: .createTime)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.dialogflow.v2.EnvironmentHistory.Entry"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.EnvironmentHistory"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [EnvironmentHistory.Entry] {
      return self.entries
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
