// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationModels
  import Foundation
  import GoogleCloudWkt

  /// The configuration for model evaluation.
  public struct EvaluationConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. Datasets used for evaluation.
    public var datasets: [InputDataset] = []

    /// Specific configurations for different models in order to do evaluation.
    public var modelSpecificConfig: OneOf_ModelSpecificConfig? = nil

    /// Initialize a new instance of `EvaluationConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = EvaluationConfig().with { $0.datasets = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case datasets = "datasets"
      case smartReplyConfig = "smartReplyConfig"
      case smartComposeConfig = "smartComposeConfig"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.datasets = try container.decode([InputDataset].self, forKey: .datasets)

      var modelSpecificConfig: OneOf_ModelSpecificConfig? = nil
      let modelSpecificConfigCheckAndSet = {
        if modelSpecificConfig != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'modelSpecificConfig'"))
        }
        modelSpecificConfig = $0
      }
      if let smartReplyConfig = try container.decodeIfPresent(
        EvaluationConfig.SmartReplyConfig?.self, forKey: .smartReplyConfig)
      {
        try modelSpecificConfigCheckAndSet(.smartReplyConfig(smartReplyConfig))
      }
      if let smartComposeConfig = try container.decodeIfPresent(
        EvaluationConfig.SmartComposeConfig?.self, forKey: .smartComposeConfig)
      {
        try modelSpecificConfigCheckAndSet(.smartComposeConfig(smartComposeConfig))
      }
      self.modelSpecificConfig = modelSpecificConfig
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.datasets, forKey: .datasets)

      if let choice = self.modelSpecificConfig {
        switch choice {
        case .smartReplyConfig(let value):
          try container.encode(value, forKey: .smartReplyConfig)
        case .smartComposeConfig(let value):
          try container.encode(value, forKey: .smartComposeConfig)
        }
      }
    }

    /// Smart reply specific configuration for evaluation job.
    public struct SmartReplyConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The allowlist document resource name.
      /// Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base
      /// ID>/documents/<Document ID>`. Only used for smart reply model.
      public var allowlistDocument: Swift.String = Swift.String()

      /// Required. The model to be evaluated can return multiple results with
      /// confidence score on each query. These results will be sorted by the
      /// descending order of the scores and we only keep the first
      /// max_result_count results as the final results to evaluate.
      public var maxResultCount: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `SmartReplyConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SmartReplyConfig().with { $0.allowlistDocument = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.dialogflow.v2.EvaluationConfig.SmartReplyConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Smart compose specific configuration for evaluation job.
    public struct SmartComposeConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// The allowlist document resource name.
      /// Format: `projects/<Project ID>/knowledgeBases/<Knowledge Base
      /// ID>/documents/<Document ID>`. Only used for smart compose model.
      public var allowlistDocument: Swift.String = Swift.String()

      /// Required. The model to be evaluated can return multiple results with
      /// confidence score on each query. These results will be sorted by the
      /// descending order of the scores and we only keep the first
      /// max_result_count results as the final results to evaluate.
      public var maxResultCount: Swift.Int32 = Swift.Int32()

      /// Initialize a new instance of `SmartComposeConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = SmartComposeConfig().with { $0.allowlistDocument = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.dialogflow.v2.EvaluationConfig.SmartComposeConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Specific configurations for different models in order to do evaluation.
    public enum OneOf_ModelSpecificConfig: Codable, Equatable, Sendable {
      /// Configuration for smart reply model evaluation.
      indirect case smartReplyConfig(EvaluationConfig.SmartReplyConfig?)
      /// Configuration for smart compose model evaluation.
      indirect case smartComposeConfig(EvaluationConfig.SmartComposeConfig?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.EvaluationConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
