// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || GeneratorEvaluations || Generators
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Providing examples in the generator (i.e. building a few-shot generator)
  /// helps convey the desired format of the LLM response.
  public struct FewShotExample: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Conversation transcripts.
    public var conversationContext: ConversationContext? = nil

    /// Optional. Key is the placeholder field name in input, value is the value of
    /// the placeholder. E.g. instruction contains "@price", and ingested data has
    /// <"price", "10">
    public var extraInfo: [Swift.String: Swift.String] = [:]

    /// Required. Example output of the model.
    public var output: GeneratorSuggestion? = nil

    /// Instruction list of this few_shot example.
    public var instructionList: OneOf_InstructionList? = nil

    /// Initialize a new instance of `FewShotExample`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = FewShotExample().with { $0.conversationContext = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case conversationContext = "conversationContext"
      case extraInfo = "extraInfo"
      case summarizationSectionList = "summarizationSectionList"
      case output = "output"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.conversationContext = try container.decodeIfPresent(
        ConversationContext.self, forKey: .conversationContext)
      self.extraInfo = try container.decode([Swift.String: Swift.String].self, forKey: .extraInfo)
      self.output = try container.decodeIfPresent(GeneratorSuggestion.self, forKey: .output)

      var instructionList: OneOf_InstructionList? = nil
      let instructionListCheckAndSet = {
        if instructionList != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'instructionList'"))
        }
        instructionList = $0
      }
      if let summarizationSectionList = try container.decodeIfPresent(
        SummarizationSectionList?.self, forKey: .summarizationSectionList)
      {
        try instructionListCheckAndSet(.summarizationSectionList(summarizationSectionList))
      }
      self.instructionList = instructionList
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.conversationContext, forKey: .conversationContext)
      try container.encode(self.extraInfo, forKey: .extraInfo)
      try container.encode(self.output, forKey: .output)

      if let choice = self.instructionList {
        switch choice {
        case .summarizationSectionList(let value):
          try container.encode(value, forKey: .summarizationSectionList)
        }
      }
    }

    /// Instruction list of this few_shot example.
    public enum OneOf_InstructionList: Codable, Equatable, Sendable {
      /// Summarization sections.
      indirect case summarizationSectionList(SummarizationSectionList?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.FewShotExample"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
