// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || Participants
  import Foundation
  import GoogleCloudWkt

  /// The response message for
  /// [Conversations.GenerateSuggestions][google.cloud.dialogflow.v2.Conversations.GenerateSuggestions].
  ///
  /// [google.cloud.dialogflow.v2.Conversations.GenerateSuggestions]: <doc:Conversations/generateSuggestions(request:)>
  public struct GenerateSuggestionsResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The answers generated for the conversation based on context.
    public var generatorSuggestionAnswers: [GenerateSuggestionsResponse.GeneratorSuggestionAnswer] =
      []

    /// The name of the latest conversation message used as context for
    /// compiling suggestion.
    ///
    /// Format: `projects/<Project ID>/locations/<Location
    /// ID>/conversations/<Conversation ID>/messages/<Message ID>`.
    public var latestMessage: Swift.String = Swift.String()

    /// Initialize a new instance of `GenerateSuggestionsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GenerateSuggestionsResponse().with { $0.generatorSuggestionAnswers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// A GeneratorSuggestion answer.
    public struct GeneratorSuggestionAnswer: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Suggestion details.
      public var generatorSuggestion: GeneratorSuggestion? = nil

      /// The name of the generator used to generate this suggestion. Format:
      /// `projects/<Project ID>/locations/<Location ID>/generators/<Generator
      /// ID>`.
      public var sourceGenerator: Swift.String = Swift.String()

      /// Answer record that uniquely identifies the suggestion. This can be used
      /// to provide suggestion feedback.
      public var answerRecord: Swift.String = Swift.String()

      /// Initialize a new instance of `GeneratorSuggestionAnswer`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GeneratorSuggestionAnswer().with { $0.generatorSuggestion = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.dialogflow.v2.GenerateSuggestionsResponse.GeneratorSuggestionAnswer"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.GenerateSuggestionsResponse"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
