// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations
  import Foundation
  import GoogleCloudWkt

  /// The request message for
  /// [Conversations.GenerateStatelessSuggestion][google.cloud.dialogflow.v2.Conversations.GenerateStatelessSuggestion].
  ///
  /// [google.cloud.dialogflow.v2.Conversations.GenerateStatelessSuggestion]: <doc:Conversations/generateStatelessSuggestion(request:)>
  public struct GenerateStatelessSuggestionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Required. The parent resource to charge for the Suggestion's generation.
    /// Format: `projects/<Project ID>/locations/<Location ID>`.
    public var parent: Swift.String = Swift.String()

    /// Optional. A section of ingested context information. The key is the name of
    /// the context reference and the value contains the contents of the context
    /// reference. The key is used to incorporate ingested context references to
    /// enhance the generator.
    public var contextReferences: [Swift.String: Conversation.ContextReference] = [:]

    /// Optional. Context of the conversation, including transcripts.
    public var conversationContext: ConversationContext? = nil

    /// Optional. A list of trigger events. Generator will be triggered only if
    /// it's trigger event is included here.
    public var triggerEvents: [TriggerEvent] = []

    /// Optional. Name of the CX SecuritySettings which is used to redact generated
    /// response. If this field is empty, try to fetch v2 security_settings, which
    /// is a project level setting. If this field is empty and no v2
    /// security_settings set up in this project, no redaction will be done.
    ///
    /// Format:
    /// `projects/<Project ID>/locations/<Location ID>/securitySettings/<Security
    /// Settings ID>`.
    public var securitySettings: Swift.String = Swift.String()

    /// Generator.
    public var generatorResource: OneOf_GeneratorResource? = nil

    /// Initialize a new instance of `GenerateStatelessSuggestionRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GenerateStatelessSuggestionRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: String, CodingKey {
      case parent = "parent"
      case generator = "generator"
      case generatorName = "generatorName"
      case contextReferences = "contextReferences"
      case conversationContext = "conversationContext"
      case triggerEvents = "triggerEvents"
      case securitySettings = "securitySettings"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.parent = try container.decode(Swift.String.self, forKey: .parent)
      self.contextReferences = try container.decode(
        [Swift.String: Conversation.ContextReference].self, forKey: .contextReferences)
      self.conversationContext = try container.decodeIfPresent(
        ConversationContext.self, forKey: .conversationContext)
      self.triggerEvents = try container.decode([TriggerEvent].self, forKey: .triggerEvents)
      self.securitySettings = try container.decode(Swift.String.self, forKey: .securitySettings)

      var generatorResource: OneOf_GeneratorResource? = nil
      let generatorResourceCheckAndSet = {
        if generatorResource != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'generatorResource'"))
        }
        generatorResource = $0
      }
      if let generator = try container.decodeIfPresent(Generator?.self, forKey: .generator) {
        try generatorResourceCheckAndSet(.generator(generator))
      }
      if let generatorName = try container.decodeIfPresent(
        Swift.String.self, forKey: .generatorName)
      {
        try generatorResourceCheckAndSet(.generatorName(generatorName))
      }
      self.generatorResource = generatorResource
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)
      try container.encode(self.contextReferences, forKey: .contextReferences)
      try container.encode(self.conversationContext, forKey: .conversationContext)
      try container.encode(self.triggerEvents, forKey: .triggerEvents)
      try container.encode(self.securitySettings, forKey: .securitySettings)

      if let choice = self.generatorResource {
        switch choice {
        case .generator(let value):
          try container.encode(value, forKey: .generator)
        case .generatorName(let value):
          try container.encode(value, forKey: .generatorName)
        }
      }
    }

    /// Generator.
    public enum OneOf_GeneratorResource: Codable, Equatable, Sendable {
      /// Uncreated generator. It should be a complete generator that includes all
      /// information about the generator.
      indirect case generator(Generator?)
      /// The resource name of the existing created generator. Format:
      /// `projects/<Project ID>/locations/<Location ID>/generators/<Generator ID>`
      case generatorName(Swift.String)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.GenerateStatelessSuggestionRequest"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
