// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || Participants
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The response message for
  /// [Conversations.GenerateSuggestions][google.cloud.dialogflow.v2.Conversations.GenerateSuggestions].
  ///
  /// [google.cloud.dialogflow.v2.Conversations.GenerateSuggestions]: <doc:ConversationsClient/generateSuggestions(request:options:)>
  public struct GenerateSuggestionsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// The answers generated for the conversation based on context.
    public var generatorSuggestionAnswers: [GenerateSuggestionsResponse.GeneratorSuggestionAnswer] =
      []

    /// The name of the latest conversation message used as context for
    /// compiling suggestion.
    ///
    /// Format: `projects/<Project ID>/locations/<Location
    /// ID>/conversations/<Conversation ID>/messages/<Message ID>`.
    public var latestMessage: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `GenerateSuggestionsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = GenerateSuggestionsResponse().with { $0.generatorSuggestionAnswers = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let generatorSuggestionAnswers = CodingKeys(stringValue: "generatorSuggestionAnswers")
      static let latestMessage = CodingKeys(stringValue: "latestMessage")

      static let _knownKeys: Set<Swift.String> = [
        "generatorSuggestionAnswers",
        "latestMessage",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [GenerateSuggestionsResponse.GeneratorSuggestionAnswer].self,
        forKey: .generatorSuggestionAnswers)
      {
        self.generatorSuggestionAnswers = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .latestMessage) {
        self.latestMessage = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.generatorSuggestionAnswers, forKey: .generatorSuggestionAnswers)
      try container.encode(self.latestMessage, forKey: .latestMessage)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// A GeneratorSuggestion answer.
    public struct GeneratorSuggestionAnswer: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Suggestion details.
      public var generatorSuggestion: GeneratorSuggestion? = nil

      /// The name of the generator used to generate this suggestion. Format:
      /// `projects/<Project ID>/locations/<Location ID>/generators/<Generator
      /// ID>`.
      public var sourceGenerator: Swift.String = Swift.String()

      /// Answer record that uniquely identifies the suggestion. This can be used
      /// to provide suggestion feedback.
      public var answerRecord: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

      /// Initialize a new instance of `GeneratorSuggestionAnswer`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = GeneratorSuggestionAnswer().with { $0.generatorSuggestion = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let generatorSuggestion = CodingKeys(stringValue: "generatorSuggestion")
        static let sourceGenerator = CodingKeys(stringValue: "sourceGenerator")
        static let answerRecord = CodingKeys(stringValue: "answerRecord")

        static let _knownKeys: Set<Swift.String> = [
          "generatorSuggestion",
          "sourceGenerator",
          "answerRecord",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        self.generatorSuggestion = try container.decodeIfPresent(
          GeneratorSuggestion.self, forKey: .generatorSuggestion)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .sourceGenerator) {
          self.sourceGenerator = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .answerRecord) {
          self.answerRecord = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleCloudWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(self.generatorSuggestion, forKey: .generatorSuggestion)
        try container.encode(self.sourceGenerator, forKey: .sourceGenerator)
        try container.encode(self.answerRecord, forKey: .answerRecord)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.dialogflow.v2.GenerateSuggestionsResponse.GeneratorSuggestionAnswer"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.GenerateSuggestionsResponse"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
