// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The request message for [ConversationsService.IngestContextReferences][].
  public struct IngestContextReferencesRequest: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Required. Resource identifier of the conversation to ingest context
    /// information for. Format: `projects/<Project ID>/locations/<Location
    /// ID>/conversations/<Conversation ID>`.
    public var conversation: Swift.String = Swift.String()

    /// Required. The context references to ingest. The key is the name of the
    /// context reference and the value contains the contents of the context
    /// reference. The key is used to incorporate ingested context references to
    /// enhance the generator.
    public var contextReferences: [Swift.String: Conversation.ContextReference] = [:]

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `IngestContextReferencesRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IngestContextReferencesRequest().with { $0.conversation = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let conversation = CodingKeys(stringValue: "conversation")
      static let contextReferences = CodingKeys(stringValue: "contextReferences")

      static let _knownKeys: Set<Swift.String> = [
        "conversation",
        "contextReferences",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .conversation) {
        self.conversation = value
      }
      if let value = try container.decodeIfPresent(
        [Swift.String: Conversation.ContextReference].self, forKey: .contextReferences)
      {
        self.contextReferences = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.conversation, forKey: .conversation)
      try container.encode(self.contextReferences, forKey: .contextReferences)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.IngestContextReferencesRequest"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
