// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Intents
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleLongRunning
  import GoogleRpc
  import GoogleWKT
  import GoogleGax
  import struct Logging.Logger

  extension Clients {
    final class IntentsLogging: IntentsStub {
      let inner: any IntentsStub
      let logger: Logger

      public init(_ inner: any IntentsStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dialogflow-v2"
        logger[metadataKey: "gcp.client.service"] = "dialogflow"
        logger[metadataKey: "gcp.experimental.swift.client"] = "Intents"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func listIntents(
        request: ListIntentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListIntentsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listIntents",
          action: {
            (r: ListIntentsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ListIntentsResponse
            in
            return try await self.inner.listIntents(request: r, options: o)
          })
      }

      public func getIntent(
        request: GetIntentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Intent {
        try await self._intercept(
          request: request,
          options: options,
          name: "getIntent",
          action: {
            (r: GetIntentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Intent
            in
            return try await self.inner.getIntent(request: r, options: o)
          })
      }

      public func createIntent(
        request: CreateIntentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Intent {
        try await self._intercept(
          request: request,
          options: options,
          name: "createIntent",
          action: {
            (r: CreateIntentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Intent
            in
            return try await self.inner.createIntent(request: r, options: o)
          })
      }

      public func updateIntent(
        request: UpdateIntentRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Intent {
        try await self._intercept(
          request: request,
          options: options,
          name: "updateIntent",
          action: {
            (r: UpdateIntentRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Intent
            in
            return try await self.inner.updateIntent(request: r, options: o)
          })
      }

      public func deleteIntent(
        request: DeleteIntentRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteIntent",
          action: { (r: DeleteIntentRequest, o: GoogleGax.RequestOptions) async throws -> Void in
            return try await self.inner.deleteIntent(request: r, options: o)
          })
      }

      public func batchUpdateIntents(
        request: BatchUpdateIntentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "batchUpdateIntents",
          action: {
            (r: BatchUpdateIntentsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.batchUpdateIntents(request: r, options: o)
          })
      }

      public func batchDeleteIntents(
        request: BatchDeleteIntentsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "batchDeleteIntents",
          action: {
            (r: BatchDeleteIntentsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.batchDeleteIntents(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listLocations",
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          name: "getLocation",
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listOperations",
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancelOperation",
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
              -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
