// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if AnswerRecords
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleWKT

  /// Represents an intent suggestion.
  public struct IntentSuggestion: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The display name of the intent.
    public var displayName: Swift.String = Swift.String()

    /// Human readable description for better understanding an intent like its
    /// scope, content, result etc. Maximum character limit: 140 characters.
    public var description: Swift.String = Swift.String()

    /// The name of the intent.
    public var intent: OneOf_Intent? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `IntentSuggestion`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = IntentSuggestion().with { $0.displayName = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let displayName = CodingKeys(stringValue: "displayName")
      static let intentV2 = CodingKeys(stringValue: "intentV2")
      static let description = CodingKeys(stringValue: "description")

      static let _knownKeys: Set<Swift.String> = [
        "displayName",
        "intentV2",
        "description",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
        self.displayName = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .description) {
        self.description = value
      }

      var intent: OneOf_Intent? = nil
      let intentCheckAndSet = {
        if intent != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'intent'"))
        }
        intent = $0
      }
      if let intentV2 = try container.decodeIfPresent(Swift.String.self, forKey: .intentV2) {
        try intentCheckAndSet(.intentV2(intentV2))
      }
      self.intent = intent
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.displayName, forKey: .displayName)
      try container.encode(self.description, forKey: .description)

      if let choice = self.intent {
        switch choice {
        case .intentV2(let value):
          try container.encode(value, forKey: .intentV2)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The name of the intent.
    public enum OneOf_Intent: Codable, Equatable, Sendable {
      /// The unique identifier of this
      /// [intent][google.cloud.dialogflow.v2.Intent]. Format: `projects/<Project
      /// ID>/locations/<Location ID>/agent/intents/<Intent ID>`.
      ///
      /// [google.cloud.dialogflow.v2.Intent]: <doc:Intent>
      case intentV2(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.IntentSuggestion"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
