// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Intents
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudGax
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// The response message for
  /// [Intents.ListIntents][google.cloud.dialogflow.v2.Intents.ListIntents].
  ///
  /// [google.cloud.dialogflow.v2.Intents.ListIntents]: <doc:IntentsClient/listIntents(request:options:)>
  public struct ListIntentsResponse: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    GoogleCloudGax._PaginatedResponse,
    Sendable
  {
    /// The list of agent intents. There will be a maximum number of items
    /// returned based on the page_size field in the request.
    public var intents: [Intent] = []

    /// Token to retrieve the next page of results, or empty if there are no
    /// more results in the list.
    public var nextPageToken: Swift.String = Swift.String()

    /// Initialize a new instance of `ListIntentsResponse`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ListIntentsResponse().with { $0.intents = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.ListIntentsResponse"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }

    public func _getPaginatedItems() -> [Intent] {
      return self.intents
    }

    public func _nextPageToken() -> Swift.String {
      return self.nextPageToken
    }
  }
#endif
