// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || Participants
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Represents a message posted into a conversation.
  public struct Message: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The unique identifier of the message.
    /// Format: `projects/<Project ID>/locations/<Location
    /// ID>/conversations/<Conversation ID>/messages/<Message ID>`.
    public var name: Swift.String = Swift.String()

    /// Required. The message content.
    public var content: Swift.String = Swift.String()

    /// Optional. The message language.
    /// This should be a [BCP-47](https://www.rfc-editor.org/rfc/bcp/bcp47.txt)
    /// language tag. Example: "en-US".
    public var languageCode: Swift.String = Swift.String()

    /// Output only. The participant that sends this message.
    public var participant: Swift.String = Swift.String()

    /// Output only. The role of the participant.
    public var participantRole: Participant.Role = Participant.Role()

    /// Output only. The time when the message was created in Contact Center AI.
    public var createTime: GoogleCloudWKT.Timestamp? = nil

    /// Optional. The time when the message was sent. For voice messages, this is
    /// the time when an utterance started.
    public var sendTime: GoogleCloudWKT.Timestamp? = nil

    /// Output only. The annotation for the message.
    public var messageAnnotation: MessageAnnotation? = nil

    /// Output only. The sentiment analysis result for the message.
    public var sentimentAnalysis: SentimentAnalysisResult? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `Message`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Message().with { $0.name = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let name = CodingKeys(stringValue: "name")
      static let content = CodingKeys(stringValue: "content")
      static let languageCode = CodingKeys(stringValue: "languageCode")
      static let participant = CodingKeys(stringValue: "participant")
      static let participantRole = CodingKeys(stringValue: "participantRole")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let sendTime = CodingKeys(stringValue: "sendTime")
      static let messageAnnotation = CodingKeys(stringValue: "messageAnnotation")
      static let sentimentAnalysis = CodingKeys(stringValue: "sentimentAnalysis")

      static let _knownKeys: Set<Swift.String> = [
        "name",
        "content",
        "languageCode",
        "participant",
        "participantRole",
        "createTime",
        "sendTime",
        "messageAnnotation",
        "sentimentAnalysis",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
        self.name = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .content) {
        self.content = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .languageCode) {
        self.languageCode = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .participant) {
        self.participant = value
      }
      if let value = try container.decodeIfPresent(Participant.Role.self, forKey: .participantRole)
      {
        self.participantRole = value
      }
      self.createTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .createTime)
      self.sendTime = try container.decodeIfPresent(
        GoogleCloudWKT.Timestamp.self, forKey: .sendTime)
      self.messageAnnotation = try container.decodeIfPresent(
        MessageAnnotation.self, forKey: .messageAnnotation)
      self.sentimentAnalysis = try container.decodeIfPresent(
        SentimentAnalysisResult.self, forKey: .sentimentAnalysis)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.name, forKey: .name)
      try container.encode(self.content, forKey: .content)
      try container.encode(self.languageCode, forKey: .languageCode)
      try container.encode(self.participant, forKey: .participant)
      try container.encode(self.participantRole, forKey: .participantRole)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.sendTime, forKey: .sendTime)
      try container.encodeIfPresent(self.messageAnnotation, forKey: .messageAnnotation)
      try container.encodeIfPresent(self.sentimentAnalysis, forKey: .sentimentAnalysis)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.Message"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
