// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Participants
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongrunning
  import GoogleCloudGax

  /// Service for managing [Participants][google.cloud.dialogflow.v2.Participant].
  ///
  /// [google.cloud.dialogflow.v2.Participant]: <doc:Participant>
  ///
  /// @Snippet(path: "ParticipantsQuickstart")
  public class ParticipantsClient: Clients.ParticipantsProtocol {
    let inner: any Clients.ParticipantsStub

    /// Creates a new `ParticipantsClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any Clients.ParticipantsStub = try Clients.ParticipantsTransport(options)
      inner = Clients.ParticipantsRetry(inner, options: options)
      if let logger = options.logger {
        inner = Clients.ParticipantsLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// Creates a new participant in a conversation.
    ///
    /// @Snippet(path: "Participants_CreateParticipant")
    public func createParticipant(
      request: CreateParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      try await self.inner.createParticipant(request: request, options: options)
    }

    /// Retrieves a conversation participant.
    ///
    /// @Snippet(path: "Participants_GetParticipant")
    public func getParticipant(
      request: GetParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      try await self.inner.getParticipant(request: request, options: options)
    }

    /// Returns the list of all participants in the specified conversation.
    ///
    /// @Snippet(path: "Participants_ListParticipants")
    public func listParticipants(
      request: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse {
      try await self.inner.listParticipants(request: request, options: options)
    }

    /// Returns the list of all participants in the specified conversation.
    ///
    /// @Snippet(path: "Participants_ListParticipants")
    public func listParticipants(
      byItem: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Participant, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listParticipants(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Updates the specified participant.
    ///
    /// @Snippet(path: "Participants_UpdateParticipant")
    public func updateParticipant(
      request: UpdateParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      try await self.inner.updateParticipant(request: request, options: options)
    }

    /// Adds a text (chat, for example), or audio (phone recording, for example)
    /// message from a participant into the conversation.
    ///
    /// Note: Always use agent versions for production traffic
    /// sent to virtual agents. See [Versions and
    /// environments](https://cloud.google.com/dialogflow/es/docs/agents-versions).
    ///
    /// @Snippet(path: "Participants_AnalyzeContent")
    public func analyzeContent(
      request: AnalyzeContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
      try await self.inner.analyzeContent(request: request, options: options)
    }

    /// Gets suggested articles for a participant based on specific historical
    /// messages.
    ///
    /// @Snippet(path: "Participants_SuggestArticles")
    public func suggestArticles(
      request: SuggestArticlesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse {
      try await self.inner.suggestArticles(request: request, options: options)
    }

    /// Gets suggested faq answers for a participant based on specific historical
    /// messages.
    ///
    /// @Snippet(path: "Participants_SuggestFaqAnswers")
    public func suggestFaqAnswers(
      request: SuggestFaqAnswersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse {
      try await self.inner.suggestFaqAnswers(request: request, options: options)
    }

    /// Gets smart replies for a participant based on specific historical
    /// messages.
    ///
    /// @Snippet(path: "Participants_SuggestSmartReplies")
    public func suggestSmartReplies(
      request: SuggestSmartRepliesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse {
      try await self.inner.suggestSmartReplies(request: request, options: options)
    }

    /// Gets knowledge assist suggestions based on historical messages.
    ///
    /// @Snippet(path: "Participants_SuggestKnowledgeAssist")
    public func suggestKnowledgeAssist(
      request: SuggestKnowledgeAssistRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse {
      try await self.inner.suggestKnowledgeAssist(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Participants_ListLocations")
    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    ///
    /// This method lists locations based on the resource scope provided in
    /// the [ListLocationsRequest.name][google.cloud.location.ListLocationsRequest.name] field: *
    /// **Global locations**: If `name` is empty, the method lists the
    /// public locations available to all projects. * **Project-specific
    /// locations**: If `name` follows the format
    /// `projects/{project}`, the method lists locations visible to that
    /// specific project. This includes public, private, or other
    /// project-specific locations enabled for the project.
    ///
    /// For gRPC and client library implementations, the resource name is
    /// passed as the `name` field. For direct service calls, the resource
    /// name is
    /// incorporated into the request path based on the specific service
    /// implementation and version.
    ///
    /// [google.cloud.location.ListLocationsRequest.name]: https://www.google.com/search?q=Swift+google.cloud.location+GoogleCloudLocation.ListLocationsRequest/name
    ///
    /// @Snippet(path: "Participants_ListLocations")
    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Gets information about a location.
    ///
    /// @Snippet(path: "Participants_GetLocation")
    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Participants_ListOperations")
    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Participants_ListOperations")
    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Participants_GetOperation")
    func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    ///
    /// @Snippet(path: "Participants_CancelOperation")
    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }

  extension Clients {
    /// A Swift protocol to mock `ParticipantsClient`.
    ///
    /// To mock `ParticipantsClient` change your functions to receive
    /// `some ParticipantsProtocol` or `any ParticipantsProtocol`
    /// and pass a mock implementation in your tests.
    public protocol ParticipantsProtocol {
      /// See `ParticipantsClient.createParticipant`.
      func createParticipant(request: CreateParticipantRequest) async throws
        -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.createParticipant`.
      func createParticipant(
        parent: Swift.String,
        participant: Participant?,
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.getParticipant`.
      func getParticipant(request: GetParticipantRequest) async throws
        -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.getParticipant`.
      func getParticipant(
        name: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.listParticipants`.
      func listParticipants(request: ListParticipantsRequest) async throws
        -> GoogleCloudDialogflowV2.ListParticipantsResponse

      /// See `ParticipantsClient.listParticipants`.
      func listParticipants(
        byItem: ListParticipantsRequest
      ) throws -> any AsyncSequence<Participant, Swift.Error>

      /// See `ParticipantsClient.listParticipants`.
      func listParticipants(
        parent: Swift.String,
      ) throws -> any AsyncSequence<Participant, Swift.Error>

      /// See `ParticipantsClient.updateParticipant`.
      func updateParticipant(request: UpdateParticipantRequest) async throws
        -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.updateParticipant`.
      func updateParticipant(
        participant: Participant?,
        updateMask: GoogleCloudWkt.FieldMask?,
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.analyzeContent`.
      func analyzeContent(request: AnalyzeContentRequest) async throws
        -> GoogleCloudDialogflowV2.AnalyzeContentResponse

      /// See `ParticipantsClient.analyzeContent`.
      func analyzeContent(
        participant: Swift.String,
        textInput: TextInput?,
      ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse

      /// See `ParticipantsClient.analyzeContent`.
      func analyzeContent(
        participant: Swift.String,
        eventInput: EventInput?,
      ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse

      /// See `ParticipantsClient.analyzeContent`.
      func analyzeContent(
        participant: Swift.String,
        audioInput: AudioInput?,
      ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse

      /// See `ParticipantsClient.suggestArticles`.
      func suggestArticles(request: SuggestArticlesRequest) async throws
        -> GoogleCloudDialogflowV2.SuggestArticlesResponse

      /// See `ParticipantsClient.suggestArticles`.
      func suggestArticles(
        parent: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse

      /// See `ParticipantsClient.suggestFaqAnswers`.
      func suggestFaqAnswers(request: SuggestFaqAnswersRequest) async throws
        -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse

      /// See `ParticipantsClient.suggestFaqAnswers`.
      func suggestFaqAnswers(
        parent: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse

      /// See `ParticipantsClient.suggestSmartReplies`.
      func suggestSmartReplies(request: SuggestSmartRepliesRequest) async throws
        -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse

      /// See `ParticipantsClient.suggestSmartReplies`.
      func suggestSmartReplies(
        parent: Swift.String,
      ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse

      /// See `ParticipantsClient.suggestKnowledgeAssist`.
      func suggestKnowledgeAssist(request: SuggestKnowledgeAssistRequest) async throws
        -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse

      /// See `ParticipantsClient.listLocations`.
      func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
        -> GoogleCloudLocation.ListLocationsResponse

      /// See `ParticipantsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `ParticipantsClient.getLocation`.
      func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
        -> GoogleCloudLocation.Location

      /// See `ParticipantsClient.listOperations`.
      func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
        -> GoogleLongrunning.ListOperationsResponse

      /// See `ParticipantsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongrunning.ListOperationsRequest
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `ParticipantsClient.listOperations`.
      func listOperations(
        name: Swift.String,
        filter: Swift.String,
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `ParticipantsClient.cancelOperation`.
      func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

      /// See `ParticipantsClient.cancelOperation`.
      func cancelOperation(
        name: Swift.String,
      ) async throws

      /// See `ParticipantsClient.createParticipant`.
      func createParticipant(
        request: CreateParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.getParticipant`.
      func getParticipant(
        request: GetParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.listParticipants`.
      func listParticipants(
        request: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse

      /// See `ParticipantsClient.listParticipants`.
      func listParticipants(
        byItem: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<Participant, Swift.Error>

      /// See `ParticipantsClient.updateParticipant`.
      func updateParticipant(
        request: UpdateParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant

      /// See `ParticipantsClient.analyzeContent`.
      func analyzeContent(
        request: AnalyzeContentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse

      /// See `ParticipantsClient.suggestArticles`.
      func suggestArticles(
        request: SuggestArticlesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse

      /// See `ParticipantsClient.suggestFaqAnswers`.
      func suggestFaqAnswers(
        request: SuggestFaqAnswersRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse

      /// See `ParticipantsClient.suggestSmartReplies`.
      func suggestSmartReplies(
        request: SuggestSmartRepliesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse

      /// See `ParticipantsClient.suggestKnowledgeAssist`.
      func suggestKnowledgeAssist(
        request: SuggestKnowledgeAssistRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse

      /// See `ParticipantsClient.listLocations`.
      func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse

      /// See `ParticipantsClient.listLocations`.
      func listLocations(
        byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

      /// See `ParticipantsClient.getLocation`.
      func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location

      /// See `ParticipantsClient.listOperations`.
      func listOperations(
        request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongrunning.ListOperationsResponse

      /// See `ParticipantsClient.listOperations`.
      func listOperations(
        byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

      /// See `ParticipantsClient.cancelOperation`.
      func cancelOperation(
        request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws
    }
  }

  // Default implementations
  extension Clients.ParticipantsProtocol {
    public func createParticipant(request: CreateParticipantRequest) async throws
      -> GoogleCloudDialogflowV2.Participant
    {
      try await self.createParticipant(request: request, options: .init())
    }

    public func createParticipant(
      request: CreateParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func createParticipant(
      parent: Swift.String,
      participant: Participant?,
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      let request = CreateParticipantRequest().with {
        $0.parent = parent
        $0.participant = participant
      }
      return try await self.createParticipant(request: request)
    }

    public func getParticipant(request: GetParticipantRequest) async throws
      -> GoogleCloudDialogflowV2.Participant
    {
      try await self.getParticipant(request: request, options: .init())
    }

    public func getParticipant(
      request: GetParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getParticipant(
      name: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      let request = GetParticipantRequest().with {
        $0.name = name
      }
      return try await self.getParticipant(request: request)
    }

    public func listParticipants(request: ListParticipantsRequest) async throws
      -> GoogleCloudDialogflowV2.ListParticipantsResponse
    {
      try await self.listParticipants(request: request, options: .init())
    }

    public func listParticipants(
      request: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listParticipants(
      byItem: ListParticipantsRequest
    ) throws -> any AsyncSequence<Participant, Swift.Error> {
      try self.listParticipants(byItem: byItem, options: .init())
    }

    public func listParticipants(
      byItem: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Participant, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listParticipants(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Participant, Swift.Error> {
      let request = ListParticipantsRequest().with {
        $0.parent = parent
      }
      return try self.listParticipants(byItem: request)
    }

    public func updateParticipant(request: UpdateParticipantRequest) async throws
      -> GoogleCloudDialogflowV2.Participant
    {
      try await self.updateParticipant(request: request, options: .init())
    }

    public func updateParticipant(
      request: UpdateParticipantRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func updateParticipant(
      participant: Participant?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleCloudDialogflowV2.Participant {
      let request = UpdateParticipantRequest().with {
        $0.participant = participant
        $0.updateMask = updateMask
      }
      return try await self.updateParticipant(request: request)
    }

    public func analyzeContent(request: AnalyzeContentRequest) async throws
      -> GoogleCloudDialogflowV2.AnalyzeContentResponse
    {
      try await self.analyzeContent(request: request, options: .init())
    }

    public func analyzeContent(
      request: AnalyzeContentRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func analyzeContent(
      participant: Swift.String,
      textInput: TextInput?,
    ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
      let request = AnalyzeContentRequest().with {
        $0.participant = participant
        $0.input = textInput.map { .textInput($0) }
      }
      return try await self.analyzeContent(request: request)
    }

    public func analyzeContent(
      participant: Swift.String,
      eventInput: EventInput?,
    ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
      let request = AnalyzeContentRequest().with {
        $0.participant = participant
        $0.input = eventInput.map { .eventInput($0) }
      }
      return try await self.analyzeContent(request: request)
    }

    public func analyzeContent(
      participant: Swift.String,
      audioInput: AudioInput?,
    ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
      let request = AnalyzeContentRequest().with {
        $0.participant = participant
        $0.input = audioInput.map { .audioInput($0) }
      }
      return try await self.analyzeContent(request: request)
    }

    public func suggestArticles(request: SuggestArticlesRequest) async throws
      -> GoogleCloudDialogflowV2.SuggestArticlesResponse
    {
      try await self.suggestArticles(request: request, options: .init())
    }

    public func suggestArticles(
      request: SuggestArticlesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func suggestArticles(
      parent: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse {
      let request = SuggestArticlesRequest().with {
        $0.parent = parent
      }
      return try await self.suggestArticles(request: request)
    }

    public func suggestFaqAnswers(request: SuggestFaqAnswersRequest) async throws
      -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse
    {
      try await self.suggestFaqAnswers(request: request, options: .init())
    }

    public func suggestFaqAnswers(
      request: SuggestFaqAnswersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func suggestFaqAnswers(
      parent: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse {
      let request = SuggestFaqAnswersRequest().with {
        $0.parent = parent
      }
      return try await self.suggestFaqAnswers(request: request)
    }

    public func suggestSmartReplies(request: SuggestSmartRepliesRequest) async throws
      -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse
    {
      try await self.suggestSmartReplies(request: request, options: .init())
    }

    public func suggestSmartReplies(
      request: SuggestSmartRepliesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func suggestSmartReplies(
      parent: Swift.String,
    ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse {
      let request = SuggestSmartRepliesRequest().with {
        $0.parent = parent
      }
      return try await self.suggestSmartReplies(request: request)
    }

    public func suggestKnowledgeAssist(request: SuggestKnowledgeAssistRequest) async throws
      -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse
    {
      try await self.suggestKnowledgeAssist(request: request, options: .init())
    }

    public func suggestKnowledgeAssist(
      request: SuggestKnowledgeAssistRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse
    {
      try await self.listLocations(request: request, options: .init())
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      try self.listLocations(byItem: byItem, options: .init())
    }

    public func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location
    {
      try await self.getLocation(request: request, options: .init())
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse
    {
      try await self.listOperations(request: request, options: .init())
    }

    public func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      try self.listOperations(byItem: byItem, options: .init())
    }

    public func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = {
        (token: Swift.String) async throws -> GoogleLongrunning.ListOperationsResponse in
        throw GoogleCloudGax.RequestError.unimplemented
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    public func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let request = GoogleLongrunning.ListOperationsRequest().with {
        $0.name = name
        $0.filter = filter
      }
      return try self.listOperations(byItem: request)
    }

    public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
      -> GoogleLongrunning.Operation
    {
      try await self.getOperation(request: request, options: .init())
    }

    public func getOperation(
      request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func getOperation(
      name: Swift.String,
    ) async throws -> GoogleLongrunning.Operation {
      let request = GoogleLongrunning.GetOperationRequest().with {
        $0.name = name
      }
      return try await self.getOperation(request: request)
    }

    public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
      try await self.cancelOperation(request: request, options: .init())
    }

    public func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      throw GoogleCloudGax.RequestError.unimplemented
    }

    public func cancelOperation(
      name: Swift.String,
    ) async throws {
      let request = GoogleLongrunning.CancelOperationRequest().with {
        $0.name = name
      }
      try await self.cancelOperation(request: request)
    }
  }
#endif
