// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Participants
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWkt
  import GoogleLongRunning
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class ParticipantsLogging: ParticipantsStub {
      let inner: any ParticipantsStub
      let logger: Logger

      public init(_ inner: any ParticipantsStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dialogflow-v2"
        logger[metadataKey: "gcp.client.service"] = "dialogflow"
        logger[metadataKey: "gcp.experimental.swift.client"] = "Participants"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func createParticipant(
        request: CreateParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant {
        try await self._intercept(
          request: request,
          options: options,
          name: "createParticipant",
          action: {
            (r: CreateParticipantRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Participant
            in
            return try await self.inner.createParticipant(request: r, options: o)
          })
      }

      public func getParticipant(
        request: GetParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant {
        try await self._intercept(
          request: request,
          options: options,
          name: "getParticipant",
          action: {
            (r: GetParticipantRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Participant
            in
            return try await self.inner.getParticipant(request: r, options: o)
          })
      }

      public func listParticipants(
        request: ListParticipantsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListParticipantsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listParticipants",
          action: {
            (r: ListParticipantsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ListParticipantsResponse
            in
            return try await self.inner.listParticipants(request: r, options: o)
          })
      }

      public func updateParticipant(
        request: UpdateParticipantRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Participant {
        try await self._intercept(
          request: request,
          options: options,
          name: "updateParticipant",
          action: {
            (r: UpdateParticipantRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Participant
            in
            return try await self.inner.updateParticipant(request: r, options: o)
          })
      }

      public func analyzeContent(
        request: AnalyzeContentRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.AnalyzeContentResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "analyzeContent",
          action: {
            (r: AnalyzeContentRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.AnalyzeContentResponse
            in
            return try await self.inner.analyzeContent(request: r, options: o)
          })
      }

      public func suggestArticles(
        request: SuggestArticlesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestArticlesResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "suggestArticles",
          action: {
            (r: SuggestArticlesRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.SuggestArticlesResponse
            in
            return try await self.inner.suggestArticles(request: r, options: o)
          })
      }

      public func suggestFaqAnswers(
        request: SuggestFaqAnswersRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "suggestFaqAnswers",
          action: {
            (r: SuggestFaqAnswersRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.SuggestFaqAnswersResponse
            in
            return try await self.inner.suggestFaqAnswers(request: r, options: o)
          })
      }

      public func suggestSmartReplies(
        request: SuggestSmartRepliesRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "suggestSmartReplies",
          action: {
            (r: SuggestSmartRepliesRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.SuggestSmartRepliesResponse
            in
            return try await self.inner.suggestSmartReplies(request: r, options: o)
          })
      }

      public func suggestKnowledgeAssist(
        request: SuggestKnowledgeAssistRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "suggestKnowledgeAssist",
          action: {
            (r: SuggestKnowledgeAssistRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.SuggestKnowledgeAssistResponse
            in
            return try await self.inner.suggestKnowledgeAssist(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listLocations",
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          name: "getLocation",
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listOperations",
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancelOperation",
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
