// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Agents
  public import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// The request message for
  /// [Agents.RestoreAgent][google.cloud.dialogflow.v2.Agents.RestoreAgent].
  ///
  /// [google.cloud.dialogflow.v2.Agents.RestoreAgent]: <doc:AgentsClient/restoreAgent(request:options:)>
  public struct RestoreAgentRequest: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. The project that the agent to restore is associated with.
    /// Format: `projects/<Project ID>`.
    public var parent: Swift.String = Swift.String()

    /// Required. The agent to restore.
    public var agent: OneOf_Agent? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `RestoreAgentRequest`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = RestoreAgentRequest().with { $0.parent = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let parent = CodingKeys(stringValue: "parent")
      static let agentUri = CodingKeys(stringValue: "agentUri")
      static let agentContent = CodingKeys(stringValue: "agentContent")

      static let _knownKeys: Set<Swift.String> = [
        "parent",
        "agentUri",
        "agentContent",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
        self.parent = value
      }

      var agent: OneOf_Agent? = nil
      let agentCheckAndSet = {
        if agent != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'agent'"))
        }
        agent = $0
      }
      if let agentUri = try container.decodeIfPresent(Swift.String.self, forKey: .agentUri) {
        try agentCheckAndSet(.agentUri(agentUri))
      }
      if let agentContent = try container.decodeIfPresent(
        Foundation.Data.self, forKey: .agentContent)
      {
        try agentCheckAndSet(.agentContent(agentContent))
      }
      self.agent = agent
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.parent, forKey: .parent)

      if let choice = self.agent {
        switch choice {
        case .agentUri(let value):
          try container.encode(value, forKey: .agentUri)
        case .agentContent(let value):
          try container.encode(value, forKey: .agentContent)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Required. The agent to restore.
    public enum OneOf_Agent: Codable, Equatable, Sendable {
      /// The URI to a Google Cloud Storage file containing the agent to restore.
      /// Note: The URI must start with "gs://".
      ///
      /// Dialogflow performs a read operation for the Cloud Storage object
      /// on the caller's behalf, so your request authentication must
      /// have read permissions for the object. For more information, see
      /// [Dialogflow access
      /// control](https://cloud.google.com/dialogflow/cx/docs/concept/access-control#storage).
      case agentUri(Swift.String)
      /// Zip compressed raw byte content for agent.
      case agentContent(Foundation.Data)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.RestoreAgentRequest"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
