// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Participants || Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Contains a speech recognition result corresponding to a portion of the audio
  /// that is currently being processed or an indication that this is the end
  /// of the single requested utterance.
  ///
  /// While end-user audio is being processed, Dialogflow sends a series of
  /// results. Each result may contain a `transcript` value. A transcript
  /// represents a portion of the utterance. While the recognizer is processing
  /// audio, transcript values may be interim values or finalized values.
  /// Once a transcript is finalized, the `is_final` value is set to true and
  /// processing continues for the next transcript.
  ///
  /// If `StreamingDetectIntentRequest.query_input.audio_config.single_utterance`
  /// was true, and the recognizer has completed processing audio,
  /// the `message_type` value is set to `END_OF_SINGLE_UTTERANCE and the
  /// following (last) result contains the last finalized transcript.
  ///
  /// The complete end-user utterance is determined by concatenating the
  /// finalized transcript values received for the series of results.
  ///
  /// In the following example, single utterance is enabled. In the case where
  /// single utterance is not enabled, result 8 would not occur.
  ///
  /// ```
  /// Num | transcript               | message_type            | is_final
  /// --- | ------------------------ | ----------------------- | --------
  /// 1   | "tube"                   | TRANSCRIPT              | false
  /// 2   | "to be a"                | TRANSCRIPT              | false
  /// 3   | "to be"                  | TRANSCRIPT              | false
  /// 4   | "to be or not to be"     | TRANSCRIPT              | true
  /// 5   | "that's"                 | TRANSCRIPT              | false
  /// 6   | "that is                 | TRANSCRIPT              | false
  /// 7   | " that is the question"  | TRANSCRIPT              | true
  /// 8   | unset                    | END_OF_SINGLE_UTTERANCE | unset
  /// 9   | ". Whether 'tis nobler"  | TRANSCRIPT              | true
  /// 10  | " in the mind"           | TRANSCRIPT              | false
  /// 11  | " in the mind to suffer" | TRANSCRIPT              | true
  /// ```
  ///
  /// Concatenating the finalized transcripts with `is_final` set to true,
  /// the complete utterance becomes "to be or not to be that is the question".
  public struct StreamingRecognitionResult: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Type of the result message.
    public var messageType: StreamingRecognitionResult.MessageType =
      StreamingRecognitionResult.MessageType()

    /// Transcript text representing the words that the user spoke.
    /// Populated if and only if `message_type` = `TRANSCRIPT`.
    public var transcript: Swift.String = Swift.String()

    /// If `false`, the `StreamingRecognitionResult` represents an
    /// interim result that may change. If `true`, the recognizer will not return
    /// any further hypotheses about this piece of the audio. May only be populated
    /// for `message_type` = `TRANSCRIPT`.
    public var isFinal: Swift.Bool = Swift.Bool()

    /// The Speech confidence between 0.0 and 1.0 for the current portion of audio.
    /// A higher number indicates an estimated greater likelihood that the
    /// recognized words are correct. The default of 0.0 is a sentinel value
    /// indicating that confidence was not set.
    ///
    /// This field is typically only provided if `is_final` is true and you should
    /// not rely on it being accurate or even set.
    public var confidence: Swift.Float = Swift.Float()

    /// Word-specific information for the words recognized by Speech in
    /// [transcript][google.cloud.dialogflow.v2.StreamingRecognitionResult.transcript].
    /// Populated if and only if `message_type` = `TRANSCRIPT` and
    /// [InputAudioConfig.enable_word_info] is set.
    ///
    /// [google.cloud.dialogflow.v2.StreamingRecognitionResult.transcript]: <doc:StreamingRecognitionResult/transcript>
    public var speechWordInfo: [SpeechWordInfo] = []

    /// Time offset of the end of this Speech recognition result relative to the
    /// beginning of the audio. Only populated for `message_type` = `TRANSCRIPT`.
    public var speechEndOffset: GoogleCloudWKT.Duration? = nil

    /// Detected language code for the transcript.
    public var languageCode: Swift.String = Swift.String()

    /// Initialize a new instance of `StreamingRecognitionResult`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamingRecognitionResult().with { $0.messageType = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Type of the response message.
    public enum MessageType: Codable, Equatable, Sendable {
      /// Not specified. Should never be used.
      case unspecified
      /// Message contains a (possibly partial) transcript.
      case transcript
      /// This event indicates that the server has detected the end of the user's
      /// speech utterance and expects no additional inputs.
      /// Therefore, the server will not process additional audio (although it may
      /// subsequently return additional results). The client should stop sending
      /// additional audio data, half-close the gRPC connection, and wait for any
      /// additional results until the server closes the gRPC connection. This
      /// message is only sent if `single_utterance` was set to `true`, and is not
      /// used otherwise.
      case endOfSingleUtterance
      /// Message contains DTMF digits.
      case dtmfDigits
      /// Message contains DTMF digits. Before a message with DTMF_DIGITS is sent,
      /// a message with PARTIAL_DTMF_DIGITS may be sent with DTMF digits collected
      /// up to the time of sending, which represents an intermediate result.
      case partialDtmfDigits
      /// This event indicates that the server has detected the beginning of human
      /// voice activity in the stream. This event can be returned multiple times
      /// if speech starts and stops repeatedly throughout the stream.
      case speechActivityBegin
      /// This event indicates that the server has detected the end of human voice
      /// activity in the stream. This event can be returned multiple times if
      /// speech starts and stops repeatedly throughout the stream.
      case speechActivityEnd
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .transcript: return 1
        case .endOfSingleUtterance: return 2
        case .dtmfDigits: return 3
        case .partialDtmfDigits: return 4
        case .speechActivityBegin: return 5
        case .speechActivityEnd: return 6
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "MESSAGE_TYPE_UNSPECIFIED"
        case .transcript: return "TRANSCRIPT"
        case .endOfSingleUtterance: return "END_OF_SINGLE_UTTERANCE"
        case .dtmfDigits: return "DTMF_DIGITS"
        case .partialDtmfDigits: return "PARTIAL_DTMF_DIGITS"
        case .speechActivityBegin: return "SPEECH_ACTIVITY_BEGIN"
        case .speechActivityEnd: return "SPEECH_ACTIVITY_END"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:MessageType/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "MESSAGE_TYPE_UNSPECIFIED": self = .unspecified
        case "TRANSCRIPT": self = .transcript
        case "DTMF_DIGITS": self = .dtmfDigits
        case "END_OF_SINGLE_UTTERANCE": self = .endOfSingleUtterance
        case "PARTIAL_DTMF_DIGITS": self = .partialDtmfDigits
        case "SPEECH_ACTIVITY_BEGIN": self = .speechActivityBegin
        case "SPEECH_ACTIVITY_END": self = .speechActivityEnd
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:MessageType/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .transcript
        case 2: self = .endOfSingleUtterance
        case 3: self = .dtmfDigits
        case 4: self = .partialDtmfDigits
        case 5: self = .speechActivityBegin
        case 6: self = .speechActivityEnd
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .transcript: return try container.encode(1)
        case .endOfSingleUtterance: return try container.encode(2)
        case .dtmfDigits: return try container.encode(3)
        case .partialDtmfDigits: return try container.encode(4)
        case .speechActivityBegin: return try container.encode(5)
        case .speechActivityEnd: return try container.encode(6)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.StreamingRecognitionResult"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
