// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || GeneratorEvaluations || Generators
  import Foundation
  @_spi(GoogleCloudInternal) public import GoogleWKT

  /// Summarization context that customer can configure.
  public struct SummarizationContext: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. List of sections. Note it contains both predefined section sand
    /// customer defined sections.
    public var summarizationSections: [SummarizationSection] = []

    /// Optional. List of few shot examples.
    public var fewShotExamples: [FewShotExample] = []

    /// Optional. Version of the feature. If not set, default to latest version.
    /// Current candidates are ["1.0"].
    public var version: Swift.String = Swift.String()

    /// Optional. The target language of the generated summary. The language code
    /// for conversation will be used if this field is empty. Supported 2.0 and
    /// later versions.
    public var outputLanguageCode: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SummarizationContext`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SummarizationContext().with { $0.summarizationSections = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let summarizationSections = CodingKeys(stringValue: "summarizationSections")
      static let fewShotExamples = CodingKeys(stringValue: "fewShotExamples")
      static let version = CodingKeys(stringValue: "version")
      static let outputLanguageCode = CodingKeys(stringValue: "outputLanguageCode")

      static let _knownKeys: Set<Swift.String> = [
        "summarizationSections",
        "fewShotExamples",
        "version",
        "outputLanguageCode",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [SummarizationSection].self, forKey: .summarizationSections)
      {
        self.summarizationSections = value
      }
      if let value = try container.decodeIfPresent([FewShotExample].self, forKey: .fewShotExamples)
      {
        self.fewShotExamples = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .version) {
        self.version = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputLanguageCode) {
        self.outputLanguageCode = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.summarizationSections, forKey: .summarizationSections)
      try container.encode(self.fewShotExamples, forKey: .fewShotExamples)
      try container.encode(self.version, forKey: .version)
      try container.encode(self.outputLanguageCode, forKey: .outputLanguageCode)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.SummarizationContext"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }
#endif
