// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Conversations || GeneratorEvaluations || Generators
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWkt

  /// Represents the section of summarization.
  public struct SummarizationSection: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Name of the section, for example, "situation".
    public var key: Swift.String = Swift.String()

    /// Optional. Definition of the section, for example, "what the customer needs
    /// help with or has question about."
    public var definition: Swift.String = Swift.String()

    /// Optional. Type of the summarization section.
    public var type: SummarizationSection.Type_ = SummarizationSection.Type_()

    /// Initialize a new instance of `SummarizationSection`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SummarizationSection().with { $0.key = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    /// Type enum of the summarization sections.
    public enum Type_: Codable, Equatable, Sendable {
      /// Undefined section type, does not return anything.
      case unspecified
      /// What the customer needs help with or has question about.
      /// Section name: "situation".
      case situation
      /// What the agent does to help the customer.
      /// Section name: "action".
      case action
      /// Result of the customer service. A single word describing the result
      /// of the conversation.
      /// Section name: "resolution".
      case resolution
      /// Reason for cancellation if the customer requests for a cancellation.
      /// "N/A" otherwise.
      /// Section name: "reason_for_cancellation".
      case reasonForCancellation
      /// "Unsatisfied" or "Satisfied" depending on the customer's feelings at
      /// the end of the conversation.
      /// Section name: "customer_satisfaction".
      case customerSatisfaction
      /// Key entities extracted from the conversation, such as ticket number,
      /// order number, dollar amount, etc.
      /// Section names are prefixed by "entities/".
      case entities
      /// Customer defined sections.
      case customerDefined
      /// Concise version of the situation section. This type is only available if
      /// type SITUATION is not selected.
      case situationConcise
      /// Concise version of the action section. This type is only available if
      /// type ACTION is not selected.
      case actionConcise
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .situation: return 1
        case .action: return 2
        case .resolution: return 3
        case .reasonForCancellation: return 4
        case .customerSatisfaction: return 5
        case .entities: return 6
        case .customerDefined: return 7
        case .situationConcise: return 9
        case .actionConcise: return 10
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .situation: return "SITUATION"
        case .action: return "ACTION"
        case .resolution: return "RESOLUTION"
        case .reasonForCancellation: return "REASON_FOR_CANCELLATION"
        case .customerSatisfaction: return "CUSTOMER_SATISFACTION"
        case .entities: return "ENTITIES"
        case .customerDefined: return "CUSTOMER_DEFINED"
        case .situationConcise: return "SITUATION_CONCISE"
        case .actionConcise: return "ACTION_CONCISE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "SITUATION": self = .situation
        case "ACTION": self = .action
        case "RESOLUTION": self = .resolution
        case "REASON_FOR_CANCELLATION": self = .reasonForCancellation
        case "CUSTOMER_SATISFACTION": self = .customerSatisfaction
        case "ENTITIES": self = .entities
        case "CUSTOMER_DEFINED": self = .customerDefined
        case "SITUATION_CONCISE": self = .situationConcise
        case "ACTION_CONCISE": self = .actionConcise
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .situation
        case 2: self = .action
        case 3: self = .resolution
        case 4: self = .reasonForCancellation
        case 5: self = .customerSatisfaction
        case 6: self = .entities
        case 7: self = .customerDefined
        case 9: self = .situationConcise
        case 10: self = .actionConcise
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .situation: return try container.encode(1)
        case .action: return try container.encode(2)
        case .resolution: return try container.encode(3)
        case .reasonForCancellation: return try container.encode(4)
        case .customerSatisfaction: return try container.encode(5)
        case .entities: return try container.encode(6)
        case .customerDefined: return try container.encode(7)
        case .situationConcise: return try container.encode(9)
        case .actionConcise: return try container.encode(10)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.SummarizationSection"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
