// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if ConversationProfiles || Conversations || Environments || Participants || Sessions
  import Foundation
  @_spi(GoogleCloudInternal) import GoogleCloudWKT

  /// Configuration of how speech should be synthesized.
  public struct SynthesizeSpeechConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. Speaking rate/speed, in the range [0.25, 4.0]. 1.0 is the normal
    /// native speed supported by the specific voice. 2.0 is twice as fast, and 0.5
    /// is half as fast. If unset(0.0), defaults to the native 1.0 speed. Any other
    /// values < 0.25 or > 4.0 will return an error.
    public var speakingRate: Swift.Double = Swift.Double()

    /// Optional. Speaking pitch, in the range [-20.0, 20.0]. 20 means increase 20
    /// semitones from the original pitch. -20 means decrease 20 semitones from the
    /// original pitch.
    public var pitch: Swift.Double = Swift.Double()

    /// Optional. Volume gain (in dB) of the normal native volume supported by the
    /// specific voice, in the range [-96.0, 16.0]. If unset, or set to a value of
    /// 0.0 (dB), will play at normal native signal amplitude. A value of -6.0 (dB)
    /// will play at approximately half the amplitude of the normal native signal
    /// amplitude. A value of +6.0 (dB) will play at approximately twice the
    /// amplitude of the normal native signal amplitude. We strongly recommend not
    /// to exceed +10 (dB) as there's usually no effective increase in loudness for
    /// any value greater than that.
    public var volumeGainDb: Swift.Double = Swift.Double()

    /// Optional. An identifier which selects 'audio effects' profiles that are
    /// applied on (post synthesized) text to speech. Effects are applied on top of
    /// each other in the order they are given.
    public var effectsProfileId: [Swift.String] = []

    /// Optional. The desired voice of the synthesized audio.
    public var voice: VoiceSelectionParams? = nil

    /// Optional. The custom pronunciations for the synthesized audio.
    public var pronunciations: [CustomPronunciationParams] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

    /// Initialize a new instance of `SynthesizeSpeechConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SynthesizeSpeechConfig().with { $0.speakingRate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let speakingRate = CodingKeys(stringValue: "speakingRate")
      static let pitch = CodingKeys(stringValue: "pitch")
      static let volumeGainDb = CodingKeys(stringValue: "volumeGainDb")
      static let effectsProfileId = CodingKeys(stringValue: "effectsProfileId")
      static let voice = CodingKeys(stringValue: "voice")
      static let pronunciations = CodingKeys(stringValue: "pronunciations")

      static let _knownKeys: Set<Swift.String> = [
        "speakingRate",
        "pitch",
        "volumeGainDb",
        "effectsProfileId",
        "voice",
        "pronunciations",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .speakingRate) {
        self.speakingRate = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .pitch) {
        self.pitch = value
      }
      if let value = try container.decodeIfPresent(Swift.Double.self, forKey: .volumeGainDb) {
        self.volumeGainDb = value
      }
      if let value = try container.decodeIfPresent([Swift.String].self, forKey: .effectsProfileId) {
        self.effectsProfileId = value
      }
      self.voice = try container.decodeIfPresent(VoiceSelectionParams.self, forKey: .voice)
      if let value = try container.decodeIfPresent(
        [CustomPronunciationParams].self, forKey: .pronunciations)
      {
        self.pronunciations = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleCloudWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.speakingRate, forKey: .speakingRate)
      try container.encode(self.pitch, forKey: .pitch)
      try container.encode(self.volumeGainDb, forKey: .volumeGainDb)
      try container.encode(self.effectsProfileId, forKey: .effectsProfileId)
      try container.encodeIfPresent(self.voice, forKey: .voice)
      try container.encode(self.pronunciations, forKey: .pronunciations)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.SynthesizeSpeechConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }
#endif
