// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Tools
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleCloudWKT
  import GoogleLongRunning
  import GoogleCloudGax
  import struct Logging.Logger

  extension Clients {
    final class ToolsLogging: ToolsStub {
      let inner: any ToolsStub
      let logger: Logger

      public init(_ inner: any ToolsStub, logger: Logger) {
        var logger = logger
        logger[metadataKey: "gcp.artifact.id"] = "google-cloud-dialogflow-v2"
        logger[metadataKey: "gcp.client.service"] = "dialogflow"
        logger[metadataKey: "gcp.experimental.swift.client"] = "Tools"
        self.inner = inner
        self.logger = logger
      }

      func _intercept<Input, Output>(
        request: Input,
        options: GoogleCloudGax.RequestOptions,
        name: Swift.String,
        action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
      ) async throws -> Output {
        var logger = logger
        logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
        logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
        logger.debug("enter  : \(request) \(options)")
        do {
          let output = try await action(request, options)
          logger.debug("success: \(request) \(options) \(output)")
          return output
        } catch let error {
          logger.debug("error  : \(request) \(options) \(error)")
          throw error
        }
      }

      public func createTool(
        request: CreateToolRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Tool {
        try await self._intercept(
          request: request,
          options: options,
          name: "createTool",
          action: {
            (r: CreateToolRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Tool
            in
            return try await self.inner.createTool(request: r, options: o)
          })
      }

      public func getTool(
        request: GetToolRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Tool {
        try await self._intercept(
          request: request,
          options: options,
          name: "getTool",
          action: {
            (r: GetToolRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Tool
            in
            return try await self.inner.getTool(request: r, options: o)
          })
      }

      public func listTools(
        request: ListToolsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListToolsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listTools",
          action: {
            (r: ListToolsRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.ListToolsResponse
            in
            return try await self.inner.listTools(request: r, options: o)
          })
      }

      public func deleteTool(
        request: DeleteToolRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "deleteTool",
          action: { (r: DeleteToolRequest, o: GoogleCloudGax.RequestOptions) async throws -> Void in
            return try await self.inner.deleteTool(request: r, options: o)
          })
      }

      public func updateTool(
        request: UpdateToolRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Tool {
        try await self._intercept(
          request: request,
          options: options,
          name: "updateTool",
          action: {
            (r: UpdateToolRequest, o: GoogleCloudGax.RequestOptions) async throws
              -> GoogleCloudDialogflowV2.Tool
            in
            return try await self.inner.updateTool(request: r, options: o)
          })
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listLocations",
          action: {
            (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.ListLocationsResponse
            in
            return try await self.inner.listLocations(request: r, options: o)
          })
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        try await self._intercept(
          request: request,
          options: options,
          name: "getLocation",
          action: {
            (r: GoogleCloudLocation.GetLocationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleCloudLocation.Location
            in
            return try await self.inner.getLocation(request: r, options: o)
          })
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        try await self._intercept(
          request: request,
          options: options,
          name: "listOperations",
          action: {
            (r: GoogleLongRunning.ListOperationsRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.ListOperationsResponse
            in
            return try await self.inner.listOperations(request: r, options: o)
          })
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        try await self._intercept(
          request: request,
          options: options,
          name: "getOperation",
          action: {
            (r: GoogleLongRunning.GetOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> GoogleLongRunning.Operation
            in
            return try await self.inner.getOperation(request: r, options: o)
          })
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
      ) async throws {
        try await self._intercept(
          request: request,
          options: options,
          name: "cancelOperation",
          action: {
            (r: GoogleLongRunning.CancelOperationRequest, o: GoogleCloudGax.RequestOptions)
              async throws -> Void in
            return try await self.inner.cancelOperation(request: r, options: o)
          })
      }
    }
  }
#endif
