// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if AnswerRecords || Conversations || GeneratorEvaluations || Generators || Participants
  import Foundation
  import GoogleCloudWkt

  /// Represents a call of a specific tool's action with the specified inputs.
  public struct ToolCall: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. A human readable short name of the tool, to be shown on the UI.
    public var toolDisplayName: Swift.String = Swift.String()

    /// Optional. A human readable description of the tool.
    public var toolDisplayDetails: Swift.String = Swift.String()

    /// Optional. The name of the tool's action associated with this call.
    public var action: Swift.String = Swift.String()

    /// Optional. The action's input parameters.
    public var inputParameters: GoogleCloudWkt.Struct? = nil

    /// Output only. Create time of the tool call.
    public var createTime: GoogleCloudWkt.Timestamp? = nil

    /// Optional. The answer record associated with this tool call.
    public var answerRecord: Swift.String = Swift.String()

    /// Output only. State of the tool call.
    public var state: ToolCall.State = ToolCall.State()

    /// Specifies the source of this tool call.
    public var source: OneOf_Source? = nil

    /// Initialize a new instance of `ToolCall`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ToolCall().with { $0.tool = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case tool = "tool"
      case cesTool = "cesTool"
      case cesToolset = "cesToolset"
      case cesApp = "cesApp"
      case toolDisplayName = "toolDisplayName"
      case toolDisplayDetails = "toolDisplayDetails"
      case action = "action"
      case inputParameters = "inputParameters"
      case createTime = "createTime"
      case answerRecord = "answerRecord"
      case state = "state"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.toolDisplayName = try container.decode(Swift.String.self, forKey: .toolDisplayName)
      self.toolDisplayDetails = try container.decode(Swift.String.self, forKey: .toolDisplayDetails)
      self.action = try container.decode(Swift.String.self, forKey: .action)
      self.inputParameters = try container.decodeIfPresent(
        GoogleCloudWkt.Struct.self, forKey: .inputParameters)
      self.createTime = try container.decodeIfPresent(
        GoogleCloudWkt.Timestamp.self, forKey: .createTime)
      self.answerRecord = try container.decode(Swift.String.self, forKey: .answerRecord)
      self.state = try container.decode(ToolCall.State.self, forKey: .state)

      var source: OneOf_Source? = nil
      let sourceCheckAndSet = {
        if source != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'source'"))
        }
        source = $0
      }
      if let tool = try container.decodeIfPresent(Swift.String.self, forKey: .tool) {
        try sourceCheckAndSet(.tool(tool))
      }
      if let cesTool = try container.decodeIfPresent(Swift.String.self, forKey: .cesTool) {
        try sourceCheckAndSet(.cesTool(cesTool))
      }
      if let cesToolset = try container.decodeIfPresent(Swift.String.self, forKey: .cesToolset) {
        try sourceCheckAndSet(.cesToolset(cesToolset))
      }
      if let cesApp = try container.decodeIfPresent(Swift.String.self, forKey: .cesApp) {
        try sourceCheckAndSet(.cesApp(cesApp))
      }
      self.source = source
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.toolDisplayName, forKey: .toolDisplayName)
      try container.encode(self.toolDisplayDetails, forKey: .toolDisplayDetails)
      try container.encode(self.action, forKey: .action)
      try container.encode(self.inputParameters, forKey: .inputParameters)
      try container.encode(self.createTime, forKey: .createTime)
      try container.encode(self.answerRecord, forKey: .answerRecord)
      try container.encode(self.state, forKey: .state)

      if let choice = self.source {
        switch choice {
        case .tool(let value):
          try container.encode(value, forKey: .tool)
        case .cesTool(let value):
          try container.encode(value, forKey: .cesTool)
        case .cesToolset(let value):
          try container.encode(value, forKey: .cesToolset)
        case .cesApp(let value):
          try container.encode(value, forKey: .cesApp)
        }
      }
    }

    /// Tool call states.
    public enum State: Codable, Equatable, Sendable {
      /// Default value.
      case unspecified
      /// The tool call has been triggered.
      case triggered
      /// The tool call requires confirmation from a human.
      case needsConfirmation
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .triggered: return 1
        case .needsConfirmation: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .triggered: return "TRIGGERED"
        case .needsConfirmation: return "NEEDS_CONFIRMATION"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "TRIGGERED": self = .triggered
        case "NEEDS_CONFIRMATION": self = .needsConfirmation
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .triggered
        case 2: self = .needsConfirmation
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .triggered: return try container.encode(1)
        case .needsConfirmation: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Specifies the source of this tool call.
    public enum OneOf_Source: Codable, Equatable, Sendable {
      /// Optional. The [tool][google.cloud.dialogflow.v2.Tool] associated with
      /// this call. Format:
      /// `projects/<ProjectID>/locations/<LocationID>/tools/<ToolID>`.
      ///
      /// [google.cloud.dialogflow.v2.Tool]: <doc:Tool>
      case tool(Swift.String)
      /// Optional. CES tool name for this call.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/apps/<AppID>/tools/<ToolID>`.
      case cesTool(Swift.String)
      /// Optional. CES toolset name for this call.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/apps/<AppID>/toolsets/ToolsetID>`.
      case cesToolset(Swift.String)
      /// Optional. CES app name for this call.
      /// Format:
      /// `projects/<ProjectID>/locations/<LocationID>/apps/<AppID>`.
      case cesApp(Swift.String)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.dialogflow.v2.ToolCall"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }
#endif
