// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if Versions
  import Foundation
  #if canImport(FoundationNetworking)
    import FoundationNetworking
  #endif
  import GoogleCloudLocation
  import GoogleLongRunning
  import GoogleWKT
  @_spi(GoogleCloudInternal) import GoogleGax

  extension Clients {
    final class VersionsTransport: VersionsStub {
      let inner: GoogleGax._HTTPClient

      public init(_ options: GoogleGax.ClientOptions = .init()) throws {
        self.inner = try GoogleGax._HTTPClient(
          from: options,
          withDefaultEndpoint: "https://dialogflow.googleapis.com",
        )
      }

      public func listVersions(
        request: ListVersionsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.ListVersionsResponse {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard, .literal("/agent")],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/versions"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/agent"),
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/versions"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard, .literal("/agent")],
              fieldName: "parent",
              expecting: "projects/*/agent"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/agent"),
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/agent"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudDialogflowV2.ListVersionsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getVersion(
        request: GetVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Version {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/agent/versions/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/agent/versions/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudDialogflowV2.Version.self, timeout: options.attemptTimeout
        ).get()
      }

      public func createVersion(
        request: CreateVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Version {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard, .literal("/agent")],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/versions"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.parent as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/agent"),
                ],
                fieldName: "parent")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/versions"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard, .literal("/agent")],
              fieldName: "parent",
              expecting: "projects/*/agent"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/agent"),
              ],
              fieldName: "parent",
              expecting: "projects/*/locations/*/agent"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        if let body = request.version {
          try req.setBody(json: body)
        }
        return try await req.rpc(
          GoogleCloudDialogflowV2.Version.self, timeout: options.attemptTimeout
        ).get()
      }

      public func updateVersion(
        request: UpdateVersionRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudDialogflowV2.Version {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.version.map({ $0.name }),
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                  .singleWildcard,
                ],
                fieldName: "version.name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.version.map({ $0.name }),
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/agent/versions/"), .singleWildcard,
                ],
                fieldName: "version.name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.version.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                .singleWildcard,
              ],
              fieldName: "version.name",
              expecting: "projects/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.version.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/agent/versions/"), .singleWildcard,
              ],
              fieldName: "version.name",
              expecting: "projects/*/locations/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        if let body = request.version {
          try req.setBody(json: body)
        }
        return try await req.rpc(
          GoogleCloudDialogflowV2.Version.self, timeout: options.attemptTimeout
        ).get()
      }

      public func deleteVersion(
        request: DeleteVersionRequest, options: GoogleGax.RequestOptions
      ) async throws {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                  .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/agent/versions/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/agent/versions/"),
                .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/agent/versions/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/agent/versions/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        _ = try await req.rpc(
          GoogleWKT.Empty.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listLocations(
        request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.ListLocationsResponse {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/locations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getLocation(
        request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleCloudLocation.Location {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
        ).get()
      }

      public func listOperations(
        request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.ListOperationsResponse {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [.literal("projects/"), .singleWildcard],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)/operations"
            var query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            let encoder = GoogleGax._QueryParameterEncoder()
            query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
            query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
            query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
            query.append(
              contentsOf: try encoder.encode(
                request.returnPartialSuccess, prefix: "returnPartialSuccess"))
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name",
              expecting: "projects/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
        ).get()
      }

      public func getOperation(
        request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
      ) async throws -> GoogleLongRunning.Operation {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0)"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.GET) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        return try await req.rpc(
          GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
        ).get()
      }

      public func cancelOperation(
        request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
      ) async throws {
        let (path, query, configure) = try {
          () throws -> (Swift.String, [URLQueryItem], (inout GoogleGax._HTTPClientRequest) -> Void)
          in
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
            guard
              let pathVariable0 = try GoogleGax._RoutingMatcher.pathValue(
                request.name as Swift.String?,
                matching: [
                  .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                  .literal("/operations/"), .singleWildcard,
                ],
                fieldName: "name")
            else {
              return nil
            }
            let path = "/v2/\(pathVariable0):cancel"
            let query = [
              URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
            ]
            return (path, query)
          }() {
            return (candidate.0, candidate.1, { $0.setMethod(.POST) })
          }
          var paths: [GoogleGax.PathMismatch] = []
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/operations/*"
            )
            paths.append(builder.build())
          }
          do {
            var builder = GoogleGax._PathMismatchBuilder()
            builder.maybeAdd(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name",
              expecting: "projects/*/locations/*/operations/*"
            )
            paths.append(builder.build())
          }
          throw GoogleGax.RequestError.binding(GoogleGax.BindingError(paths: paths))
        }()
        var req = try await self.inner.newRequest(
          percentEncodedPath: path, query: query, options: options)
        configure(&req)
        req.addHeader(name: GoogleGax._HeaderNames.apiClient, value: Clients.clientHeader)
        _ = try await req.rpc(
          GoogleWKT.Empty.self, timeout: options.attemptTimeout
        ).get()
      }
    }
  }
#endif
